refactor(tm2/pkg/autofile): use SIGTERM
gnolang/gno pull request #1006
Opened 2023-07-31 08:22 UTC by ilgooz

In order to make gnovm compatible with WASM target we need to use a signal other than SIGHUP. [Here](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/syscall/syscall_js.go;l=91-98) is the full list of support signals.

I changed the code to use SIGTERM instead, as it seemed closest to what SIGHUP does.

2023-07-31 09:12 UTC, moul requested changes
Changing `SIGHUP` to `SIGTERM` isn't ideal. `SIGHUP` is meant to be used multiple times in one process—it's a low-level signal for DevOps intent. `SIGTERM` just kills the process, making signal catching inefficient.

I'd say keep `SIGHUP` but disable the signal catching in an `autofile_unsupported.go` file where it's not supported (`//+build wasm`).

---

Also, not sure why SIGHUP just closes files without rotating logs. We should either scrap this or actually make it do a full log rotation. Thoughts, @jaekwon?

2023-07-31 09:53 UTC, ilgooz commented
Thanks for the review. I will make the changes, but before moving forward, is there a possibility of `autofile` being refactored or a plan to change its behavior in a way that it won't depend on signals or SIGHUP?

2023-07-31 13:22 UTC, moul commented
No refactoring plans yet, but I reckon we should reorganize the code (keeping the API as is). That'll let us have multiple implementations with build constraints and make wasm an official target for our packages.

Basically, it's about organizing our code files (in general) to make them easier to maintain, both for wasm and non-wasm.

As for completely axing signal handling or moving it to the main while letting the library follow the main configuration, that's probably the right path. But, I'm holding off for @jaekwon's take on my previous comment.

2023-08-01 14:00 UTC, ilgooz commented
Closing in favor of https://github.com/gnolang/gno/pull/1012.

2023-08-01 14:00 UTC, closed without merging