feat(stdlib): add `path` package
gnolang/gno pull request #1065
Opened 2023-08-23 14:20 UTC by gfanton

simply add `path` package to stdlib, needed by `net/url` package (and probably some other packages)

<details><summary>Contributors' checklist...</summary>

- [X] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [X] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2023-08-24 13:45 UTC, thehowl requested changes
I've had a look through the Go native implementation. There doesn't seem to be any dependency on packages/features we can't currently support (imports are on `errors`, `utf8` and `internal/bytealg`, all of which already exist as packages, and I don't see any channels/goros being used).

Could we have this as gno code instead of a native injection?

Also, `gnovm/docs/go-gno-compatibility.md` should be updated, too. :)

2023-08-24 15:32 UTC, gfanton commented
> I've had a look through the Go native implementation. There doesn't seem to be any dependency on packages/features we can't currently support (imports are on errors, utf8 and internal/bytealg, all of which already exist as packages, and I don't see any channels/goros being used).
Could we have this as gno code instead of a native injection?

Sure, that make sense! I wasn't sure about preferring one location over another. I thought that if no modifications were needed, or if there were only a few methods to add, it would be more efficient to place this directly in the `stdlib` file rather than creating a specific gno package directory.

2023-08-24 17:41 UTC, thehowl commented on gnovm/docs/go-gno-compatibility.md
> +| path                                        | full     |
I'd say it's `partial` if there's no `match.go` -- so either add also `match.go` or change this to partial :)

2023-08-28 19:18 UTC, thehowl approved these changes

2023-08-28 19:19 UTC, merged