feat: use `modfile` package to write modfile
gnolang/gno pull request #1077
Opened 2023-08-28 10:31 UTC by harry-hov

The previous implementation manually iterates over the `Require` and `Replace` and writes them in the string var. which is very inefficient and doesn't handles comments and other cases. 

Changed it use `modfile` package to write modfile(gno.mod/go.mod). It uses `*modfile.FileSyntax`. Copied few methods from `modfile` package to manupulate `*modfile.FileSyntax`.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2023-08-28 11:03 UTC, harry-hov commented on gnovm/pkg/gnomod/file.go
> +func (f *File) Write(fname string) error {
Only this function is to review. Rest of the code is copied.

2023-08-31 16:32 UTC, moul approved these changes

2023-09-11 15:51 UTC, harry-hov commented
This PR is required for gno mod tidy support (i.e PR #1035). Since PR #1035 is [🌟 Wanted for Launch]. 

Changing status from [🔵 Not Needed for Launch] -> [🌟 Wanted for Launch]

cc: @moul

2023-09-13 21:40 UTC, zivkovicmilos requested changes
Essentially the same comment I had about #1078:
https://github.com/gnolang/gno/pull/1078#pullrequestreview-1625492448

Please see:
https://app.codecov.io/gh/gnolang/gno/pull/1077

2023-10-05 20:01 UTC, merged