fix: append nil to an array was causing a panic
gnolang/gno pull request #1177
Opened 2023-09-27 07:57 UTC by mvertes

This is a particular case of Go append builtin where the array type is inferred from the first argument. We detect an untyped nil passed as argument, then we convert it to the array type prior to proceed further. It fixes further consistency checks and value generation.

Fixes #1136.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2023-09-27 08:16 UTC, mvertes commented
Seeing if I can make the fix even more generic and also handle any untyped constant value, as to fix also #1149.

2023-10-04 23:40 UTC, thehowl approved these changes
LGTM :clap:

2023-10-04 23:40 UTC, thehowl commented on gnovm/pkg/gnolang/preprocess.go
> +							var arg1 Expr = Call(tx, arg)
Nit:

```suggestion
							arg1 := Call(tx, arg)
```

Even if it returns *CallExpr, it doesn't matter, no?

2023-10-04 23:42 UTC, thehowl commented
> Does that also fix the bug we had on gnochess #1170 ?

Not as far as I can see, alas. This is specifically tackling constant expressions in append; #1170 is about the internal pointers not being fixed with appends.

2023-10-05 01:38 UTC, piux2 commented
@thehowl, @moul,

Issue #1136 and issue #1149 are rooted in different issues. 

Regarding #1136:
In Go, it's not permissible to append a nil to concrete types like []int. In the test case discussed, error is a built-in interface type. In Go, the default zero value for an interface type is nil, so it's allowable to append a nil to a slice of type []error. However, the behavior described in issue #1149 is different. If one attempts to append a nil to []int, it should, and typically does, cause a panic. Notably, after this fix, this panic no longer occurs when appending a nil to []int.

For #1149:
As the error message hinted. The core of the problem lies in converting variadic generic type arguments into a slice before they are passed into the append function. It's important to note that this issue isn't exclusive to append but also impacts any function that accepts variadic generic type arguments.


We will need to dig more and fix it at the root.

2023-10-05 01:49 UTC, thehowl commented
> In Go, it's not permissible to append a nil to concrete types like []int. In the test case discussed, error is a built-in interface type. In Go, the default zero value for an interface type is nil, so it's allowable to append a nil to a slice of type []error. However, the behavior described in issue #1149 is different. If one attempts to append a nil to []int, it should, and typically does, cause a panic. Notably, after this fix, this panic no longer occurs when appending a nil to []int.

I was surprised to find out you're right (because it seemed to me that this PR didn't special-case nil):

```go
package main

func main() {
        var ints []int
        ints = append(ints, nil, nil)
        println(ints)
}

// Output: slice[(0 int),(0 int)]
```

This works correctly. However, this is actually a phenomenon caused by a root issue: we allow converting `nil` to `int` (and presumably other types):

```go
package main

func main() {
        println(int(nil))
}

// Output: 0
```

I think the approach @mvertes has used is correct (given `append([]T, T...)`, attempt to convert the variadic args into T before appending). However, we suffer a different problem about `nil`, thus allowing to do what you mentioned (appending `nil` to a slice of ints).

>As the error message hinted. The core of the problem lies in converting variadic generic type arguments into a slice before they are passed into the append function. It's important to note that this issue isn't exclusive to append but also impacts any function that accepts variadic generic type arguments.

This one, empirically, does not check out (for the last statement). Try this one, and playing out with changing it (from master):

```gopackage main

func main() {
	var n []int
	x := 2
	vari(n, 1, x)
}

func vari(n []int, params ...interface{}) {}
```

It's append which is special in this case.

2023-10-05 01:49 UTC, piux2 commented
> Does that also fix the bug we had on gnochess #1170 ?
> 
> Note that to reproduce it, you need to broadcast multiple tx, so the current test system in `tests/files` cannot be used.

For issue #1170, the root cause is located in realm.go, the underlying problem arises from the underlying array of the slice not being marked as "dirty" during the persistence of a realm object when that object is assigned to itself. I'm still evaluating the issue to identify an optimal solution.

2023-10-05 01:50 UTC, piux2 commented
> LGTM, @piux2 can you make a complementary review, please? 

Yes, done

2023-10-05 03:04 UTC, piux2 commented
I think here is the right place to fix #1149
https://github.com/gnolang/gno/blob/ce258b16cf27d10ac8e62abde2675c3b4ce76b6f/gnovm/pkg/gnolang/types.go#L1163

and add following  condition:



		+ if isUntyped(varg.T) {
	        +   vargt =	defaultTypeOf(varg.T)
		+ }else{
				vargt = varg.T
		 + }

2023-10-05 16:42 UTC, piux2 commented
We will have further discussion and update the changes

2023-10-06 07:06 UTC, piux2 requested changes
we will dig further

2023-12-07 17:19 UTC, thehowl approved these changes

2023-12-11 16:18 UTC, zivkovicmilos commented
@piux2 
Ping for unblocking this PR

2023-12-21 17:37 UTC, jaekwon commented on gnovm/pkg/gnolang/preprocess.go
>  						}
maybe at least some enclosing else, to differentiate two disjoint cases.

2023-12-21 17:42 UTC, jaekwon commented
LGTM

2024-01-10 12:44 UTC, thehowl commented
@mvertes I've made a [small commit](https://github.com/gnolang/gno/pull/1177/commits/04614ecea4ba0b02e0ea4d6349c81315b776bde2) to address the comment by Jae. Then I noticed a small chance for optimisation (re-using the result of `Call`), then I also fixed some tests that was failing on the CI :)

If the changes look good to you, please merge. The code's been reviewed by Jae, if there are further changes requested they can be made in a separate PR :)

2024-01-10 13:17 UTC, merged

2024-01-10 16:54 UTC, piux2 commented
> @piux2 ping

@mvertes sorry, I thought it was already approved 

@thehowl thank you.