docs(grammatical): correct typos and improve grammar
gnolang/gno pull request #1321
Opened 2023-10-30 20:24 UTC by AbhineshJha

This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
No functional changes have been made; this is purely a maintenance update.

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2023-10-31 04:23 UTC, AbhineshJha commented
please review sir @jaekwon @moul

2023-11-07 20:19 UTC, thehowl requested changes

2023-11-07 20:19 UTC, thehowl commented on PHILOSOPHY.md
> +* Go is chosen for the faster development of modular components, not for maximum speed.
Better before.

2023-11-09 18:27 UTC, thehowl approved these changes

2023-11-09 18:27 UTC, merged