make tests run faster
gnolang/gno pull request #1417
Opened 2023-12-07 04:45 UTC by petar-dambovaliev

solves [issue](https://github.com/gnolang/gno/issues/1406)

2024-01-07 21:15 UTC, thehowl commented
@petar-dambovaliev ready for review?

I'll try to take a look at it this week. (It's close to the top of my review-list, so should be able to take a look at it, but no guarantees).

Thanks for the hard work.

2024-01-08 11:50 UTC, zivkovicmilos commented
> @petar-dambovaliev ready for review?
> 
> I'll try to take a look at it this week. (It's close to the top of my review-list, so should be able to take a look at it, but no guarantees).
> 
> Thanks for the hard work.

Should be ready for viewing as far as I know

2024-01-16 15:32 UTC, zivkovicmilos commented on gnovm/pkg/gnolang/debug.go
> -type debugging bool
![jic9nec7mae31](https://github.com/gnolang/gno/assets/16712663/c8f5dbd7-31ab-4ab5-8e8e-1c5369ac85d7)

cc @ajnavarro

2024-01-16 16:09 UTC, zivkovicmilos approved these changes
Ran this locally, seems to shave ~1min on my machine for `make test` in the `gnovm` subfolder 🎉 

Thank you for removing globals. I see this PR as a good start 👍

2024-01-22 11:03 UTC, ajnavarro reviewed
doing a partial review, GitHub is failing to load the diff.

2024-02-02 17:42 UTC, thehowl reviewed
So, I had a feeling that adding new pointers to all of these structs may actually not be the best thing for performance. The tests may run faster, but overall execution is actually _slower_:

```
goos: linux
goarch: amd64
pkg: github.com/gnolang/gno/gnovm/pkg/gnolang
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
                                │ bench_master.txt │           bench_1406.txt            │
                                │      sec/op      │   sec/op     vs base                │
Benchdata/fib.gno_param:4-16          32.27µ ±  5%   32.47µ ± 7%        ~ (p=0.393 n=10)
Benchdata/fib.gno_param:8-16          228.8µ ±  5%   236.0µ ± 1%   +3.15% (p=0.000 n=10)
Benchdata/fib.gno_param:16-16         11.02m ±  4%   10.91m ± 5%        ~ (p=0.481 n=10)
Benchdata/loop.gno-16                 493.3n ± 11%   698.5n ± 6%  +41.60% (p=0.000 n=10)
Benchdata/matrix.gno_param:3-16       653.9µ ±  4%   707.7µ ± 6%   +8.22% (p=0.004 n=10)
Benchdata/matrix.gno_param:4-16       1.862m ±  3%   2.081m ± 4%  +11.74% (p=0.000 n=10)
Benchdata/matrix.gno_param:5-16       6.822m ±  6%   7.643m ± 5%  +12.04% (p=0.000 n=10)
Benchdata/matrix.gno_param:6-16       34.66m ±  5%   38.16m ± 5%  +10.11% (p=0.000 n=10)
geomean                               572.6µ         630.8µ       +10.17%
```

```
go test -v -bench 'Benchdata' -run 'NONE' -count 10 | tee ~/throw/bench_1406.txt
```

These are tests done with the benchmarking system I added in #1624 (note it specifically targets benchmarking execution, not preprocessing) and as you can see there is an average 10% more time taken on each operation.

I think this makes clear our need for good benchmarking and proves the point of setting this up in #1624. Please, if you see problems with the methodology, or see a benchmark which disproves these benchmarks, do point them out. I pushed the branch with this branch + the changes in #1624 in [`1406-with-bench`](https://github.com/gnolang/gno/tree/1406-with-bench)

I think there are some foundational ideas in this PR which are good, some which need to be iterated before we can have tests which are both parallelized but don't sacrifice execution-time performance.

Thanks!

2024-02-02 17:42 UTC, thehowl commented on gnovm/pkg/gnolang/values.go
So, I don't think we necessarily need what @ajnavarro mentioned (ie. making `debugging` a singleton like it was before the PR), but I do think we need to split its two uses, which actually completely avoids what happened in this file: that every file type now gets the debugging variable.

I suggest that for all cases where the debugging variable guards an additional check like the vast majority of the ones here, that we instead opt for the same solution I'm proposing to disable debugging at compile time: build tags. These are all checks which provide "additional safety", so I would have a value like `const Safety = true`, enabled by default, that can be disabled with build tag `-tags gno_optimize` or `-tags gno_nosafety`.

2024-02-02 17:43 UTC, thehowl requested changes
Sorry, meant to indicate request changes.

2024-02-22 14:00 UTC, petar-dambovaliev commented on gnovm/pkg/gnolang/nodes_string.go
> +	// NOTE: for  selector issues:
intellij find and replace

2024-02-22 14:01 UTC, petar-dambovaliev commented on gnovm/Makefile
> +GOTEST_FLAGS ?= -timeout=30m
It is giving out a lot of spam. You generally don't care for verbose when running all tests.
You care about verbose when running a single test.

2024-02-22 14:05 UTC, petar-dambovaliev commented
https://github.com/gnolang/gno/pull/1417#discussion_r1476316421

2 threads appending a slice without a synchronization mechanism is a concurrency violation.

2024-05-15 10:58 UTC, closed without merging