fix: incorrect pointer type comparision
gnolang/gno pull request #1601
Opened 2024-01-30 09:43 UTC by ltzmaxwell

This is a fix to #1569 .

- [x] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-02-28 00:45 UTC, deelawn requested changes
Looks pretty good.  I think we need to guard against invalid type comparisons.

2024-02-28 00:45 UTC, deelawn commented on gnovm/pkg/gnolang/op_expressions.go
> +	elt := xv.TV.T
Are the changes in this file necessary? The `TV.T` doesn't appear to be consumed later during the equality check. The tests that have been added still pass with these changes excluded.

2024-02-29 18:45 UTC, piux2 commented
I think we should convert []byte("ABCD") to  []byte{65, 66, 67, 68} in  preprocess.

2024-02-29 20:01 UTC, piux2 commented
I think we should try to find a way to convert []byte("ABCDEFG") to []byte{65, 66, 67, 68} in preprocess.

2024-03-29 12:06 UTC, zivkovicmilos commented
@ltzmaxwell 
Can you please check @deelawn's comments on this PR? 🙏

2024-04-01 15:00 UTC, ltzmaxwell commented on gnovm/pkg/gnolang/values.go
> +	bv := &TypedValue{ // heap alloc, so need to compare value rather than pointer in isEql(), line 482
that make sense.

2024-04-01 15:31 UTC, ltzmaxwell commented
> @ltzmaxwell Can you please check @deelawn's comments on this PR? 🙏

Updated 🙏 .

2024-04-03 15:28 UTC, petar-dambovaliev approved these changes

2024-04-08 20:36 UTC, deelawn commented
> > @ltzmaxwell Can you please check @deelawn's comments on this PR? 🙏
> 
> Updated 🙏 .

I don't think that fixed it -- see this comment https://github.com/gnolang/gno/pull/1601#discussion_r1505134477

2024-04-09 00:15 UTC, ltzmaxwell commented on gnovm/pkg/gnolang/op_binary.go
> +			rpv := rv.V.(PointerValue)
Thank you @deelawn for the review. 🙏 . This seems to be another problem. If the assertion failed the comparison should be invalid (invalid operation: mismatched type xxx and xxx). or, even rv.V is pointer value they can be incomparable either.

think:

package main

func main() {
intPtr := new(int8)
*intPtr = 5

i := 0
println(intPtr == &i)
}

I believe this is something fixed in https://github.com/gnolang/gno/pull/1426.

see here:
https://github.com/gnolang/gno/blob/5b83cdbfdbfd6e95e41b126b46ac5d62f5fe0088/gnovm/tests/files/types/0a02.gno

https://github.com/gnolang/gno/blob/3d148f6d3df828e3621c6670f743e312e73001a6/gnovm/tests/files/types/0a03.gno

WDYT?

2024-04-09 00:30 UTC, deelawn approved these changes

2024-04-09 11:58 UTC, merged