chore: add more validation to MsgRun
gnolang/gno pull request #1646
Opened 2024-02-08 18:31 UTC by leohhhn

## Description

This PR adds more validation to `MsgRun` in the VM.

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-02-15 17:34 UTC, harry-hov commented on tm2/pkg/std/memfile.go
> +	}
maybe?
```suggestion
	if memPkg.IsEmpty() {
		return errors.New(fmt.Sprintf("found an empty package %q", mempkg.Path))
	}
```

2024-02-19 11:16 UTC, leohhhn commented on tm2/pkg/std/memfile.go
> +	}
[dc6bf24](https://github.com/gnolang/gno/pull/1646/commits/dc6bf24ef8c5daffb3e22b592516059b090234b7)

2024-02-22 12:14 UTC, zivkovicmilos commented
Please give me a minute to review this, I'm sensing it's a touchy PR 🙏

2024-02-22 17:02 UTC, gfanton approved these changes

2024-02-29 17:52 UTC, thehowl commented
cc/ @jaekwon, from review meeting:

Is there any reason why `ValidateBasic` is called basic? Should the checks perform within it be very fast, "basic" or whatever? Can we add the `mempkg` check in there, or would it create problems?

2024-03-30 03:22 UTC, zivkovicmilos requested changes
Why would you move the `Package` validation outside the keeper methods, that validate it upon execution, and into `ValidateBasic`, which should be a quick sanity check for validity?

We use `Package.Validate` and `ValidateBasic` in the same sense how we use `CheckTx` and `DeliverTx` - one is a quick sanity check, and the other is detailed validation (VM processing).

We execute `ValidateBasic` for top-level validations (ex. when the node receives a tx message from gossip), and do additional validations (execution validations) when the node actually commits it to the VM.

I am not convinced this change is valid

2024-03-30 03:22 UTC, zivkovicmilos commented on tm2/pkg/std/memfile.go
> +		return errors.New(fmt.Sprintf("package is nil"))
You should format errors with `fmt.Errorf`.

Looking at this again, you don't even format an error here, this entire call is useless - define it as a package-level error

2024-03-30 03:22 UTC, zivkovicmilos commented on tm2/pkg/std/memfile.go
> +		return errors.New(fmt.Sprintf("package %q contains no files", mempkg.Name))
You should format errors with `fmt.Errorf`

2024-03-30 03:22 UTC, zivkovicmilos commented on tm2/pkg/std/memfile.go
>  func (mempkg *MemPackage) Validate() error {
Please add unit tests for `MemPackage` validation

2024-03-30 03:22 UTC, zivkovicmilos commented on gno.land/pkg/sdk/vm/msgs.go
> +	}
Where is this covered?

2024-03-30 03:22 UTC, zivkovicmilos commented on gno.land/pkg/sdk/vm/msgs.go
> +	}
Where is this covered?

2024-03-30 03:22 UTC, zivkovicmilos commented on gno.land/pkg/sdk/vm/errors.go
> +func (e InvalidPackageError) Error() string { return "package validation failed" }
Please add a documentation reference in this PR as to what is a "valid package" 🙏

2024-04-29 19:19 UTC, zivkovicmilos commented
@leohhhn what's the status on this PR?

cc @Kouteki

2024-04-29 19:43 UTC, leohhhn commented
@zivkovicmilos 

This has been hanging mainly because I assume I will spend too much time due to my lack of knowledge on how the keeper works - I will give it a shot this week and try to incorporate the change you requested. Will ping you when I'm done 👍

2024-06-04 06:20 UTC, closed without merging