chore: add r/demo/print
gnolang/gno pull request #1785
Opened 2024-03-18 07:33 UTC by grepsuzette

add /r/demo/print

This realm simply prints user address and similar information.          
It can help designing wallet connection.                                
                                                                        
See also r/demo/echo (to print various thing like user address)

2024-03-18 08:42 UTC, leohhhn commented
@grepsuzette 

We have a whole saga on why `_test.pkg.bft` is failing. Ignore it :)

2024-03-21 16:54 UTC, thehowl commented on examples/gno.land/r/demo/print/gno.mod
> +module gno.land/r/demo/priint
```suggestion
module gno.land/r/demo/print
```

2024-03-27 07:37 UTC, zivkovicmilos requested changes
I'm not sure I completely understand the usage of a Realm like this. What value does this add to the `examples` directory? I am also not completely sold on naming it `/r/demo/print`

2024-03-27 07:37 UTC, zivkovicmilos commented on examples/gno.land/r/demo/print/print.gno
> + */
Nitpick: please use `//` notation instead of `/**/`

2024-06-04 05:32 UTC, closed without merging