feat: add devx faucet account
gnolang/gno pull request #1789
Opened 2024-03-18 12:57 UTC by mazzy89

Add to the genesis the faucet for the devx team.

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-03-18 13:28 UTC, ilgooz requested changes
can we also add g13d7jc32adhc39erm5me38w5v7ej7lpvlnqjk73

2024-03-18 13:50 UTC, zivkovicmilos approved these changes

2024-03-18 14:33 UTC, leohhhn approved these changes

2024-03-19 00:28 UTC, ilgooz approved these changes

2024-03-19 08:24 UTC, merged