fix: guard against infinite loops and recursion
gnolang/gno pull request #1807
Opened 2024-03-21 02:14 UTC by deelawn

Closes #1805

This sets the maximum cycles to the [same as genesis](https://github.com/gnolang/gno/blob/7596f4262dd474ef99dc3fba6155c63d1e439af2/contribs/gnodev/pkg/dev/node.go#L416) in the case where it is set to zero which indicates infinite cycles.  This is important so that the VM can provide immediate feedback that something is wrong rather than hanging forever.  See the associated issue and the provided test in the PR for examples of how to reproduce the issue.
<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-03-21 15:38 UTC, thehowl reviewed
I'm not entirely sure about these changes.

If you execute these on Gno.land, these will fail, I'm pretty sure, as you'd get "cpu cycle overrun" already. So these fail in `gno run` and `gno test`, which from this PR would be excluded with the new limit.

The way I see it, we should have a limit on the amount of frames that can be created (ie. a stack overflow error), which is for both local testing and the blockchain context, but nothing more than the existing CPU overrun checks for infinte for loops. wdyt?

2024-03-21 15:38 UTC, thehowl commented on gnovm/pkg/gnolang/machine.go
> +	IsTest        bool
wdyt if instead of adding `IsTest`, we made `MaxAllocBytes` and `MaxCycles` have default values if `== 0`, and be unlimited if `< 0`?

2024-03-21 15:38 UTC, thehowl commented on gnovm/pkg/gnolang/machine.go
> +		maxCycles = 10_000_000
can we centralize this in a constant like DefaultMaxCycles?

2024-03-21 17:49 UTC, thehowl commented
<details><summary>Initial comment</summary>
<p>

From the review meeting:

- Let's make sure that `gno run` and `gno test` are not limited in VM cycles execution
- And have a default value for max VM cycles


</p>
</details> 

TBD w/ @deelawn @piux2

2024-03-23 03:59 UTC, petar-dambovaliev requested changes
In my opinion, the bottom of infinite recursion/loop should be when there is no more gas.

2024-03-26 17:02 UTC, piux2 commented
also we need to remove the code that configs VM parameters from command flag.

2024-03-26 22:32 UTC, deelawn commented
> In my opinion, the bottom of infinite recursion/loop should be when there is no more gas. That means that the check needs to be added in the VM.

This will be the fallback value if, for some reason, something prevents the machine from halting execution when the gas runs out.

2024-03-27 12:14 UTC, petar-dambovaliev approved these changes

2024-03-28 17:46 UTC, moul commented
Hey, 

I support this change. But in the long time, I believe we should make it configurable by the blockchain instead of hardcoding it. See #1856.

Also, linked with #828.

2024-03-29 05:54 UTC, zivkovicmilos commented
> Hey,
> 
> I support this change. But in the long time, I believe we should make it configurable by the blockchain instead of hardcoding it. See #1856.
> 
> Also, linked with #828.

💯 % agreed. I'll see to tackle this soon

2024-03-30 01:00 UTC, merged

2024-04-03 15:41 UTC, piux2 reviewed
LGTM