ci: test gno.land when changing gnovm and tm2
gnolang/gno pull request #2215
Opened 2024-05-27 13:35 UTC by thehowl

I'd like if we had good tests and decoupled components that could make this unnecessary. However I believe it's still the case that modifying something in tm2 and gnovm can create issues on gno.land without showing up on the CI, seeing as it is the component that strictly depends on both tm2 and gnovm.

2024-06-03 14:31 UTC, ajnavarro requested changes
I think this is going to mess up code coverage...

2024-06-06 16:08 UTC, thehowl commented
>I think this is going to mess up code coverage...

Wdym? How could this mess up the coverage?

2024-06-13 15:47 UTC, ajnavarro approved these changes
Nevermind, I thought that codecov will be confused if we added the same coverage for several tags, but it might not be the case.

2024-06-18 16:16 UTC, moul approved these changes

2024-06-18 16:40 UTC, merged