fix(gnokey): JSON-ify the query results from the 'gnokey' query
gnolang/gno pull request #2249
Opened 2024-05-31 04:20 UTC by linhpn99

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-05-31 17:01 UTC, thehowl requested changes
I don't like this. The default output for `vm/qeval` should be simple and human-readable; JSON is helpful for working with scripting but harms readability. Ie. I want the result of `vm/qeval` to be simple to understand and close to what I get reading the result of `maketx call`.

I suggest having a `-output` flag, defaulting to `text`, but which can be set to `json`, for the gnokey `query`, `maketx -broadcast` and `broadcast` commands. This should print the JSON response from the node, with little modification. In the case of `qeval`, this can be simply `qres.Response`.

2024-06-01 01:54 UTC, linhpn99 commented on tm2/pkg/crypto/keys/client/query.go
> +	}
agree with u, so that i will make a second PR to add flag --broadcast

2024-06-01 02:52 UTC, linhpn99 commented
> I don't like this. The default output for `vm/qeval` should be simple and human-readable; JSON is helpful for working with scripting but harms readability. Ie. I want the result of `vm/qeval` to be simple to understand and close to what I get reading the result of `maketx call`.
> 
> I suggest having a `-output` flag, defaulting to `text`, but which can be set to `json`, for the gnokey `query`, `maketx -broadcast` and `broadcast` commands. This should print the JSON response from the node, with little modification. In the case of `qeval`, this can be simply `qres.Response`.

agree with u, so that i will make a second PR to add flag --broadcast.

2024-06-01 03:49 UTC, linhpn99 commented on tm2/pkg/crypto/keys/client/query.go
> +	}
i'm ready for the second review

2024-06-04 08:32 UTC, moul commented
We need to align this pull request with #1776 to ensure consistency and idiomatic usage.

cc @gfanton

2025-04-08 16:07 UTC, thehowl commented
I'm closing this PR as the author has not been contributing to Gno for a while.

Feel free to re-open this PR, or fork this PR and propose a new one, considering the latest comments and any surrounding discussion.

2025-04-08 16:07 UTC, closed without merging