docs: rename docs/reference/reference.md to README.md
gnolang/gno pull request #2258
Opened 2024-06-02 04:32 UTC by grepsuzette

Propose to rename it.

2024-06-02 04:45 UTC, grepsuzette commented
Not sure if good idea, but ChatGPT:

Renaming a `foo/foo.md` file to `foo/README.md` within a documentation tree can be a good practice in many cases. 

The README.md file is commonly recognized as the primary documentation entry point in many projects. By renaming foo.md to README.md, you are following a standard convention that makes it easier for others to quickly understand the purpose of the file and the content it holds when they navigate through the documentation tree. This can improve the overall clarity and organization of your documentation.

2024-06-03 09:25 UTC, thehowl commented
this makes sense to me, seeing also as the urls on the website are not connected to the filename; but cc @leohhhn.

2024-06-07 18:09 UTC, leohhhn approved these changes
This makes sense 👍 

Could you do it for every index file? Each section has one.

2024-06-12 13:00 UTC, grepsuzette commented
> This makes sense 👍
> 
> Could you do it for every index file for consistency? Each section has one.

Yep, I'll see if there are others!

2024-06-13 03:51 UTC, moul commented on docs/assets/how-to-guides/creating-grc721/mynonfungibletoken-2.gno
why removing this file?

2024-06-13 03:54 UTC, moul commented
I noticed you removed several files. Was this intentional?

The PR title no longer matches the changes. Please update it.

I suggest reviewing #2125 as it's related and both are needed.

2024-06-13 04:00 UTC, moul requested changes
Please review #2125 first, as I believe this PR conflicts with its final purpose.

Once there is a clear action plan for those two pull requests, please let me know, and I'll review this PR again.

2024-06-13 04:23 UTC, grepsuzette commented on docs/assets/how-to-guides/creating-grc721/mynonfungibletoken-2.gno
This file got removed in https://github.com/gnolang/gno/commit/c67eff69349f0ba9ec15452f0ee149dbb2899643 (notice it's not in https://github.com/gnolang/gno/tree/master/docs/assets/how-to-guides anymore) but it was still present in my PR.

I got conflicts such as files deleted or removed on master since this PR was opened and tried to solve them manually. 

I was actually reading about rebase vs merge workflows because of that. 

Will review #2125, thanks.

2024-06-13 07:28 UTC, moul commented on docs/assets/how-to-guides/creating-grc721/mynonfungibletoken-2.gno
Okay, I see. I think your PR is just unsynchronized with the master branch. You should update your branch.

Essentially, fix the Git-related issues, and this PR should no longer have the following:

![CleanShot 2024-06-13 at 09 27 36](https://github.com/gnolang/gno/assets/94029/74221e6b-baa2-4298-b6e7-468c11ecb5d7)

2025-01-13 18:05 UTC, closed without merging

2025-01-13 18:05 UTC, thehowl commented
feel free to re-open.