fix(gnoweb): allow some fields to be textarea in realm help (#591)
gnolang/gno pull request #2296
Opened 2024-06-06 09:41 UTC by grepsuzette

Partially addresses #591.

When gnoweb encounters a field with a name starting 
by "body", it will use a textarea in the realm's help for that field, 
instead of a linear text input.

Although using the name of a field is not ideal, 
the method used here can help build a better solution.

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-06-06 09:45 UTC, grepsuzette commented
This is the simply the same as the old #626 which I messed by merging instead of rebasing...

### How was it tested

The order sequentiality was tested accessing the ?help of a realm having this function:

`func FourFields(title string, body string, location string, body2 string) {}`

![Screenshot 2024-06-06 at 16-37-52 Gno land -](https://github.com/gnolang/gno/assets/350354/4d45cd98-d67c-4395-b559-dbfc4d7af370)

2024-07-07 14:47 UTC, alexiscolin approved these changes
Yeah, using the name is not very robust but might do the work for now. Thank you!

2025-01-11 16:28 UTC, moul requested changes
Let's not use a name pre/suffix.

@jefft0 is improving the API that generates the $help page, including the function comments. I think we can follow an existing documentation comment format and allow people to name the variables as they prefer for human readability, rather than to please a tool.

2025-01-19 16:01 UTC, grepsuzette commented
Yes this was originally a PR from 2023. Closing this.

2025-01-19 16:01 UTC, closed without merging