feat(gnokey): add querying realm balances
gnolang/gno pull request #2470
Opened 2024-06-30 21:13 UTC by leohhhn

## Description

Closes: #2469 

This PR adds code to the handler in `gnokey` that extends the `bank/balances` functionality to allow users to fetch the balance of a realm given its pkgpath, ie `bank/balances/gno.land/r/demo/wugnot`.

Initially I wanted to implement this functionality in the handler for tm2/sdk/bank, but in order to not introduce more tm2<>gno dependencies, I did it in the `gnokey` query handler. Then, I realized that that handler is also in tm2 :/

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
- [x] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-07-02 01:29 UTC, moul requested changes
good idea, but it should be implemented from sdk/vm.Handlers, not from keys/client.

2024-07-02 10:37 UTC, leohhhn commented
@moul 

The issue is the following; you can find only the VM queries in `gno.land/pkg/sdk/vm`:

```
QueryPackage = "package"
QueryStore   = "store"
QueryRender  = "qrender"
QueryFuncs   = "qfuncs"
QueryEval    = "qeval"
QueryFile    = "qfile"
```

On the other hand, `bank/balances` is querying the banker which lives separately, in `tm2/sdk/bank`. 

I did this change in `keys/client` instead of in `tm2/sdk/bank` because I thought we wanted to keep tm2 & the banker agnostic to the VM they're communicating with. Let me know if I'm wrong on this.

With my implementation, `gnokey` would do the argument parsing locally and and the query would not change on the side of the chain.

2024-07-04 00:54 UTC, moul commented
> The issue is the following; you can find only the VM queries in gno.land/pkg/sdk/vm:

Yes, that's exactly where I recommend implementing it: directly from this package, instead of from `keys/client`.

2024-07-04 00:56 UTC, moul commented on tm2/pkg/crypto/keys/client/query.go
> +		pkgAddr := gnolang.DerivePkgAddr(pkgPath)
`tm2` should not import `gnovm/` or `gno.land/`.

2025-02-10 17:27 UTC, thehowl commented
What's the state on this one?

2025-02-10 17:29 UTC, Gno2D2 commented
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))
 🟢 Pending initial approval by a review team member, or review from tech-staff


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 The pull request was created from a fork (head branch repo: leohhhn/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

<details><summary>Pending initial approval by a review team member, or review from tech-staff</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 Not (🔴 Pull request author is a member of the team: tech-staff)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 If
    ├── 🟢 Condition
    │   └── 🟢 Or
    │       ├── 🔴 At least 1 user(s) of the organization reviewed the pull request (with state "APPROVED")
    │       ├── 🟢 At least 1 user(s) of the team tech-staff reviewed pull request
    │       └── 🔴 This pull request is a draft
    └── 🟢 Then
        └── 🟢 Not (🔴 This label is applied to pull request: review/triage-pending)

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

2025-02-10 18:00 UTC, leohhhn commented
Will put it to draft, this is a non-prio for now.

2025-08-13 10:59 UTC, closed without merging