B-Tree added
gnolang/gno pull request #2677
Opened 2024-08-11 20:09 UTC by gfant

<details><summary>Contributors' checklist...</summary>

- [X] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [X] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

Added B-Tree structure so data can be mantained ordered without using too much operations.

2024-08-23 02:57 UTC, gfant commented
Is there something I could do to help with the merging of this PR, @thehowl , @ajnavarro @leohhhn ? (Thank you in advance!)

2024-08-26 08:59 UTC, ajnavarro approved these changes

2024-08-26 08:59 UTC, ajnavarro commented on examples/gno.land/p/demo/btree/btree.gno
> +		return nil, errors.New("Invalid t")
Nit:
```suggestion
		return nil, errors.New("invalid t")
```

2024-08-26 08:59 UTC, ajnavarro commented on examples/gno.land/p/demo/btree/btree.gno
> +func (bt *BTree) insertNonFull(x *BTreeNode, k Content) {
```suggestion
// insertNonFull inserts if the node isn't full
func (bt *BTree) insertNonFull(x *BTreeNode, k Content) {
```

2024-08-30 03:48 UTC, gfant commented
Updated test to adapt to new error message.

2024-10-19 17:37 UTC, wyhaines commented
There is a bug in the implementation, likely in the delete/fill/merge handling.

If you insert a large number of entries into the tree, and then start deleting them, you will run into a situation where you get a `.: test pkg: panic: slice index out of bounds: 3 (len=3)` type error.

This is likely related to the recursion near the bottom of the `delete` function, but there is interplay with the fill/merge functionality. Something is just not quite right, and while it's possible to fix the slice out of bounds, when one does that, after doing a number of deletes, one starts to get keys that are no longer reachable.

This is an incomplete test, but it serves to illustrate the problem:

```
func TestStress(t *testing.T) {
  tree, _ := NewBTree(4)

  for j := 0; j < 1000; j++ {
    tree.Insert(Content{Key: j, Value: j})
  }

  if tree.GetSize() != 1000 {
    t.Errorf("Expected size of 1000; got %d\n", tree.GetSize())
  }

  for j := 0; j < 1000; j++ {
    found, err := tree.Search(j)
    if found.Key != j {
      t.Errorf("Search for %d expected to find %d, but got %d\n", j, j, found.Key)
    }
  }

  for j := 0; j < 1000; j += 2 {
    tree.Delete(j)
  }
}
```

2024-10-19 17:39 UTC, wyhaines requested changes
There is a bug in the implementation, likely in the delete/fill/merge handling.

If you insert a large number of entries into the tree, and then start deleting them, you will run into a situation where you get a  `.: test pkg: panic: slice index out of bounds: 3 (len=3)` type error.

This is likely related to the recursion near the bottom of the delete function, but there is interplay with the fill/merge functionality. Something is just not quite right, and while it's possible to fix the slice out of bounds, when one does that, after doing a number of deletes, one starts to get keys that are no longer reachable.

This is an incomplete test, but it serves to illustrate the problem:

```
func TestStress(t *testing.T) {
  tree, _ := NewBTree(4)

  for j := 0; j < 1000; j++ {
    tree.Insert(Content{Key: j, Value: j})
  }

  if tree.GetSize() != 1000 {
    t.Errorf("Expected size of 1000; got %d\n", tree.GetSize())
  }

  for j := 0; j < 1000; j++ {
    found, err := tree.Search(j)
    if found.Key != j {
      t.Errorf("Search for %d expected to find %d, but got %d\n", j, j, found.Key)
    }
  }

  for j := 0; j < 1000; j += 2 {
    tree.Delete(j)
  }
}
```

2025-01-31 08:03 UTC, leohhhn commented
We merged a separate b-tree implementation some time back. @gfant thank you for this effort, but we'll be closing this PR.

2025-01-31 08:03 UTC, closed without merging