feat: verifySignature function
gnolang/gno pull request #2776
Opened 2024-09-09 20:09 UTC by Villaquiranm

<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-10-10 07:29 UTC, notJoon commented
CI failed. could you please check and fix this?

2024-10-11 17:20 UTC, Villaquiranm commented
> CI failed. could you please check and fix this?

I think it is ok just one does not want to finish do not know why

2024-10-18 09:49 UTC, notJoon approved these changes
I checked it purely through test runs, it executed well without any significant issues. 

Although I also looked into related issues, it might be better to conduct a more detailed review in the next stage.

remove: `review/triage-pending`

2024-10-23 14:32 UTC, thehowl commented
I'm still not convinced by this approach. I think we should have verification happen at the protol level rather than happen at the Gno level. Can we not use the message signers as I pointed out in the discussion on #2777?

2025-01-08 08:32 UTC, zivkovicmilos requested changes
I like the direction, but we need better naming and more tests 🙏 

Otherwise, good to merge 🚀

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/tests/files/std12_stdlibs.gno
> +package main
Why not add multiple stdlib tests for valid and invalid signature verification?

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/stdlibs/std/native_test.go
> +	if signer != info.GetAddress().String() {
`assert.Equal`

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/stdlibs/std/native_test.go
> +	if signatureValid {
`assert.True`

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/stdlibs/std/native_test.go
> +	info, err := kb.CreateAccount("user", DefaultAccount_Seed, pass, pass, 0, 0)
You don't need to use the keybase to generate a key, you can just use something like `ed25519.GenPrivKey()` or even better `secp256k1.GenPrivKey()`, which will mimic what the keybase is doing under the hood

Not to mention it is exponentially faster 🚀

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/stdlibs/std/native_test.go
> +func TestVerify(t *testing.T) {
Should be named `TestVerifyECSignature` or something similar

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/stdlibs/std/native.go
> +func X_verifySignature(pubKeySigner string, msg string, signature string) (bool, string) {
Please, let's rename this method to something more descriptive, since this is the sig verification method for both ed25519 and secp256k1. What do you think about `VerifyECSignature`, as the name for the native method?

Also, I'd rename the args here:
- `pubKeySigner` -> `bech32PubKey` (to be explicit)
- `msg` -> `rawData` (and please make this a `[]byte`)
- change the type of `signature` to `[]byte`

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/stdlibs/std/native.gno
> +func VerifySignature(pubKeySigner string, signature string, msg string) (bool, string) {
Check my comment below for the rename 🙏

2025-01-08 08:32 UTC, zivkovicmilos commented on gnovm/stdlibs/std/native_test.go
> +const DefaultAccount_Seed = "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast"
Please, drop this

2025-01-08 08:39 UTC, zivkovicmilos commented
> I'm still not convinced by this approach. I think we should have verification happen at the protol level rather than happen at the Gno level. Can we not use the message signers as I pointed out in the discussion on #2777?

@thehowl 
I think what @Villaquiranm is aiming at is having generic signature verification, the signature doesn't have to originate from a message / transaction, but can be arbitrary data we sign and push to the chain (not sure what this use case would be, and why we'd verify sigs on chain).

I'm not necessarily for or against this idea, but I'd like to hear why @Villaquiranm would need signature verification on-chain through native methods 👀 

For reference, Ethereum has native methods in Solidity for deriving the address from the ECDSA signature, but not for verifying it (there are library contracts that people can import and use) -- which supports the argument that sig verification is something that should be done off-chain

2025-01-08 08:40 UTC, Gno2D2 commented
#### 🛠 PR Checks Summary
 🔴 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🔴 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: TERITORI/gno)

```
### Then
```
🔴 Requirement not satisfied
└── 🔴 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

2025-02-28 11:08 UTC, thehowl commented
Seeing the doubts expressed by me and Milos, and the lack of response, and the feature freeze, I'd close this PR for the time being, and maybe reconsider it at another time if there is a strong reason for its addition.

Let's revisit post launch.

2025-02-28 11:08 UTC, closed without merging