chore: put collective ownership on most CODEOWNERS
gnolang/gno pull request #2788
Opened 2024-09-12 17:28 UTC by thehowl

This PR comes following a discussion in today's "review meeting", where we talked about our current approach to ownership.

One aspect which was talked about was that the current set-up for CODEOWNERS is very "noisy". Opening up a PR often entails tagging many people and teams for review. To try to overcome this, I removed most rules which tried to find "exact people" to own a piece of the code, in favour of collective ownership on the `tech-staff`, `security`, `devrels` and `devops` teams, depending on which part of the code is interested.

I wrote a few lines explaining the differences between assigning a directory to a team, a person, or a team + person, and how the CODEOWNERS file should be interpreted. I wrote them trying to match the practical implications of the CODEOWNERS file (= who gets picked in the requested reviewers) with the "social" / organizational implications.

2024-09-12 17:41 UTC, leohhhn commented
Just to set expectations upfront: @gnolang/devrels are not codeowners of the docs since some time back - check out [this comment](https://github.com/gnolang/docs.gno.land/pull/45#issuecomment-2189394007).

However, I don't mind providing inputs.

2024-09-12 17:49 UTC, leohhhn commented on .github/CODEOWNERS
> +/examples/gno.land/r/morgan/          @thehowl
can you add 
`/examples/gno.land/r/leon/` for me please? so I don't have to make a separate PR
```suggestion
/examples/gno.land/r/morgan/          @thehowl
/examples/gno.land/r/leon/                @leohhhn
```

2024-09-12 21:24 UTC, moul requested changes
Interesting! Let's discuss it during the upcoming retreat before we merge.

2024-09-13 08:22 UTC, sw360cab commented
I would suggest adding `@gnolang/devops` to `.github/workflows`

2024-09-13 08:49 UTC, Kouteki commented on .github/CODEOWNERS
> +#   where X is the primary developer. However, ownership here can be ignored if
Should we suggest to the individual code owner to unassign themselves if the change is small enough?

2024-09-26 14:16 UTC, thehowl commented
This PR will be pending until @aeddi figures out a bot for github which will have a wider scope, and cover some of the things the CODEOWNERS file was currently attempting to do :)

2024-10-21 22:53 UTC, thehowl commented
Looking to actually [remove CODEOWNERS](https://github.com/gnolang/gno/issues/1007#issuecomment-2427655633)

2024-10-21 22:53 UTC, closed without merging