feat(examples): malek's namespace
gnolang/gno pull request #2831
Opened 2024-09-22 14:52 UTC by MalekLahbib

related to [leon's PR](https://github.com/gnolang/gno/pull/2740), and [namespaces doc](https://docs.gno.land/concepts/namespaces)
<details><summary>Contributors' checklist...</summary>

- [ ] Added new tests, or not needed, or not feasible
- [ ] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [ ] Updated the official documentation or not needed
- [ ] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [ ] Added references to related issues and PRs
- [ ] Provided any useful hints for running manual tests
- [ ] Added new benchmarks to [generated graphs](https://gnoland.github.io/benchmarks), if any. More info [here](https://github.com/gnolang/gno/blob/master/.benchmarks/README.md).
</details>

2024-09-23 08:46 UTC, leohhhn requested changes
Hey, thanks for the PR. We would like to have as many examples as possible for different home realms, as we will have a competition of them soon. It would be cool if you were to experiment and add different things. Copying the same code does not bring that much value to the examples/ folder.

2024-09-23 08:49 UTC, thehowl commented
> Hey, thanks for the PR. We would like to have as many examples as possible for different home realms, as we will have a competition of them soon. It would be cool if you were to experiment and add different things. Copying the same code does not bring that much value to the examples/ folder.

mhh. it's ok, he can modify later?

it can be a start of a fork. :)

2024-09-23 08:50 UTC, MalekLahbib commented
> Hey, thanks for the PR. We would like to have as many examples as possible for different home realms, as we will have a competition of them soon. It would be cool if you were to experiment and add different things. Copying the same code does not bring that much value to the examples/ folder.

I didn't have no inspiration on what to add. What could you suggest?

2024-09-30 10:11 UTC, leohhhn commented
@thehowl 

> mhh. it's ok, he can modify later?
> 
> it can be a start of a fork. :)

Sure, but I still disagree; why not start the fork in the PR?
In the state it is right now, the PR will add little to no value to the codebase, simply because it's mostly a copy. People can use permissionless deployments for this type of stuff.

I want to see diversity and creativity in the examples, not a bunch of almost identical packages. [Here](https://github.com/gnolang/hackerspace/pull/85) is a PR made after my home realm Live Coding session, which has a completely different (albeit bad because of HTML) approach. 

@MalekLahbib

> I didn't have no inspiration on what to add. What could you suggest?

Sorry, I don't have any ideas, and this is _your_ home page. Try to draw inspiration from other websites, or make something completely new 😄

2025-01-19 22:48 UTC, thehowl commented
Feel free to re-open following suggestions, closing for housekeeping.

2025-01-19 22:48 UTC, closed without merging