feat(stdlibs/time)!: remove mono
gnolang/gno pull request #3193
Opened 2024-11-25 10:44 UTC by MikaelVallenet

based on #3016 and fix #851

> :warning: I'd like to point out that this PR seems touchy to me and include some potential breaking changes, and I think a thorough review is important before merge.

-----

## Description

The purpose of this Pull Request is to simplify the Time pkg, which comes from Go, in order to remove unnecessary functions for Gno. 

This Pull Request removes the concept of monotonic clock, which corresponds to the time since the start of the program, often used to calculate the time interval between two events more reliably.

```go
type Time struct {
	sec  int64
	nsec int32
        loc *Location
}
```

Most of the PR is code deletion, not addition, especially the bitwise logic. [see article](https://articles.singee.me/golang-time?locale=en)
I'd like to take this opportunity to say that I haven't answered the testing question, because the PR seems tedious enough to review as it is.

> For what concerns testing, I think it's reasonable at the start of gno test to set a TimestampSeconds at the UNIX timestamp of starting the test. Or maybe we want it fixed in time... but, seeing as this is the testing environment, if we end up wanting to change it we can just change it later.
You may want to move internal/os.Sleep to the testing stdlib's time. Or maybe, let's have a SetNow which can take a time.Time to be set as the current value of Now().
_Originally posted by @thehowl in https://github.com/gnolang/gno/issues/851#issuecomment-2429753760_

## BREAKING CHANGE :warning: 

## Core Structure Changes
- Simplified `Time` struct from `{wall uint64, ext int64, loc *Location}` to just `{sec int64, nsec int32, loc *Location}` [time.gno]
- Removed monotonic clock functionality completely [time.gno]
- Removed all bitwise operations related to wall time and monotonic clock [time.gno]

## Removed Functions and Variables

### time.gno
- `Time.stripMono()` - Removed monotonic clock stripping
- `Time.setMono(m int64)` - Removed monotonic clock setting
- `Time.mono()` - Removed monotonic clock reading
- `Time.nsec()` - Replaced with direct field access
- `Time.sec()` - Replaced with direct field access
- `runtimeNano()` - Removed runtime clock reading
- `hasMonotonic`, `maxWall`, `minWall`, `nsecMask`, `nsecShift` constants - Removed
- `startNano` variable - Removed

## Modified Functions (remove monotonic logic)

### time.gno
- `Time.addSec()` 
- `Time.After(u Time)` 
- `Time.Before(u Time)`
- `Time.Equal(u Time)`
- `Time.Add(d Duration)`
- `Time.Sub(u Time)` 
- `Since(t time)` 
- `Until(t time)`
- `Time.Truncate()` 
- `Time.Round()`
- `Now()` - Simplified to not track monotonic time

### format.gno
- `Time.String()` - Simplified to remove monotonic clock representation

## Impact on Other Files

### Examples and Tests
- All time string representations now show  without monotonic clock component
----

# Archive :book:  (Before i revert to keep only the monotonic clock changes before we agree on how we want to handle the chain time injection)

## Description

The purpose of this Pull Request is to simplify the Time pkg, which comes from Go, in order to remove unnecessary functions for Gno. 

This Pull Request removes the concept of monotonic clock, which corresponds to the time since the start of the program, often used to calculate the time interval between two events more reliably.

```go
type Time struct {
	sec  int64
	nsec int32
        loc *Location
}
```

I removed the local location to replace it with chainTz that is loaded from injected chainTZ data

Most of the PR is code deletion, not addition, especially the bitwise logic. [see article](https://articles.singee.me/golang-time?locale=en)

I'd like to take this opportunity to say that I haven't answered the testing question, because the PR seems tedious enough to review as it is.

> For what concerns testing, I think it's reasonable at the start of gno test to set a TimestampSeconds at the UNIX timestamp of starting the test. Or maybe we want it fixed in time... but, seeing as this is the testing environment, if we end up wanting to change it we can just change it later.
You may want to move internal/os.Sleep to the testing stdlib's time. Or maybe, let's have a SetNow which can take a time.Time to be set as the current value of Now().
_Originally posted by @thehowl in https://github.com/gnolang/gno/issues/851#issuecomment-2429753760_

<details><summary>Contributors' checklist...</summary>

- [x] Added new tests, or not needed, or not feasible
- [x] Provided an example (e.g. screenshot) to aid review or the PR is self-explanatory
- [x] Updated the official documentation or not needed
- [x] No breaking changes were made, or a `BREAKING CHANGE: xxx` message was included in the description
- [x] Added references to related issues and PRs
- [x] Provided any useful hints for running manual tests
</details>

## BREAKING CHANGE :warning: 

## Core Structure Changes
- Simplified `Time` struct from `{wall uint64, ext int64, loc *Location}` to just `{sec int64, nsec int32, loc *Location}` [time.gno]
- Removed monotonic clock functionality completely [time.gno]
- Made a variable (`ChainTZ`) instead of Local [timezoneinfo.gno]
- Removed all bitwise operations related to wall time and monotonic clock [time.gno]

## Removed Functions and Variables

### time.gno
- `Time.Local()` - Renamed Time.ChainTZ and returns ChainTZ instead
- `Time.stripMono()` - Removed monotonic clock stripping
- `Time.setMono(m int64)` - Removed monotonic clock setting
- `Time.mono()` - Removed monotonic clock reading
- `Time.nsec()` - Replaced with direct field access
- `Time.sec()` - Replaced with direct field access
- `runtimeNano()` - Removed runtime clock reading
- `hasMonotonic`, `maxWall`, `minWall`, `nsecMask`, `nsecShift` constants - Removed
- `startNano` variable - Removed

### timezoneinfo.gno
- `Local` variable - Removed
- `localLoc` variable - Removed
- `LoadLocation(name string)` - Removed to prioritize `LoadLocationFromTZData` 

## Modified Functions

### time.gno
- `Time.unixSec()` - Simplified to directly access `t.sec` field
- `Time.addSec()` - Simplified to only modify `t.sec` field
- `Time.After(u Time)` - Simplified to direct field comparison without monotonic clock
- `Time.Before(u Time)` - Simplified to direct field comparison without monotonic clock
- `Time.Equal(u Time)` - Simplified to direct field comparison without monotonic clock
- `Time.IsZero()` - Simplified to check `t.sec` and `t.nsec` directly
- `Time.Add(d Duration)` - Simplified to not handle monotonic clock
- `Time.Sub(u Time)` - Simplified to not use monotonic clock for comparisons
- `Time.AddDate()` - Modified to always use `ChainTZ`
- `Time.Nanosecond()` - Modified to directly access `t.nsec` field
- `Time.UnixMilli()` - Modified to use direct field access
- `Time.UnixMicro()` - Modified to use direct field access
- `Time.UnixNano()` - Modified to use direct field access
- `Time.Truncate()` - Simplified to not strip monotonic time
- `Time.Round()` - Simplified to not strip monotonic time
- `div()` - Modified to use direct field access
- `Now()` - Simplified to not track monotonic time
- `Since(t Time)` - Simplified to not use monotonic optimizations
- `Until(t Time)` - Simplified to not use monotonic optimizations
- `Date(year, month, day, hour, min, sec, nsec, loc)` - Forces use of `ChainTZ` regardless of provided location
- `Unix()`, `UnixMilli()`, `UnixMicro()` - Simplified implementations

### format.gno
- `Time.String()` - Simplified to remove monotonic clock representation
- `Time.GoString()` - Modified local representation to chain representation
- `Parse(layout, value string)` - Modified to use `ChainTZ` instead of `Local` :question: 
- `parse()` - change the name of param ``local`` to ``chainTZ`` :question: 

## Added Functions and Variables

### timezoneinfo.gno
- Added `ChainTZ` as the default timezone, replace Local
- Added `chainLoc` variable initialized by loading chainTZData or UTC if empty
- `chainTZParamData()` - injected func [...]

2024-12-09 17:01 UTC, moul commented
I was also considering adding a global variable to the standard library that is set to a custom value during its `func init()`. This would allow it to function like a "dynamic" constant within the package, eliminating the need to pass this fixed value everywhere. It would also make the standard library independent of parameters, std, and so on. 

What do you think?

2024-12-10 08:54 UTC, MikaelVallenet commented
> I was also considering adding a global variable to the standard library that is set to a custom value during its `func init()`. This would allow it to function like a "dynamic" constant within the package, eliminating the need to pass this fixed value everywhere. It would also make the standard library independent of parameters, std, and so on.
> 
> What do you think?

Yeah i think it could be a good idea, at least for now and make it easier to implement.
I will update the code to do this in the next days :rocket:

2025-03-20 06:59 UTC, jefft0 commented
@MikaelVallenet , in the description can you please add a BREAKING CHANGE section, with the changes to function return values (shown in the changed tests), and the removed types and functions?

2025-03-20 07:17 UTC, jefft0 commented on gnovm/stdlibs/time/time.gno
> +	_, _, _, _, isDST := ChainTZ.lookup(t.Unix())
Please add a test for this change.

2025-03-20 08:02 UTC, jefft0 commented
@MikaelVallenet , can you please merge master? For me, when I merge master locally, the following test fails.
```
gno test examples/gno.land/r/demo/groups
```

2025-03-21 13:05 UTC, MikaelVallenet commented
i'll look at it A.S.A.P to update the PR and answer your requests

2025-03-27 14:12 UTC, MikaelVallenet commented on gnovm/stdlibs/time/time.gno
> +	_, _, _, _, isDST := ChainTZ.lookup(t.Unix())
done: b45fc23
I'd like to know why a test is required for this particular function

2025-03-27 14:14 UTC, MikaelVallenet commented
> @MikaelVallenet , can you please merge master? For me, when I merge master locally, the following test fails.
> 
> ```
> gno test examples/gno.land/r/demo/groups
> ```

It should work now! :pray: 
Thanks for review

2025-03-28 08:23 UTC, jefft0 approved these changes
The (many) breaking changes are documented. There are tests for new functions. CI checks pass. Master is merged. Ready for core devs to review. (Note that this is Milestone mainnet beta.)

2025-03-31 13:56 UTC, ajnavarro approved these changes
LGTM

2025-03-31 13:56 UTC, ajnavarro commented on gnovm/stdlibs/time/timezoneinfo.gno
> +var chainLoc Location = Location{name: "UTC"}
```suggestion
// chainLoc is kept separate so that ChainTZ can always refer to &chainLoc,
// ensuring it never returns a nil *Location, even if a client improperly
// modifies ChainTZ.
var chainLoc Location = Location{name: "UTC"}
```

2025-03-31 15:52 UTC, MikaelVallenet commented
I want to mention that I have a special feeling (a bit like impostor syndrome) after modifying Go's time package, and I think that before merging, multiple detailed reviews might be necessary.

2025-04-01 01:56 UTC, petar-dambovaliev approved these changes
I hesitantly approve this.

2025-04-01 01:58 UTC, petar-dambovaliev commented
> I want to mention that I have a special feeling (a bit like impostor syndrome) after modifying Go's time package, and I think that before merging, multiple detailed reviews might be necessary.

Don't worry. I am there with you.
Many years ago i deleted Rob Pike's code from the actual Go's time package.

2025-04-01 18:11 UTC, thehowl commented on gnovm/stdlibs/time/time.gno
> +	nsec int32
Hey, sorry for the late review on this.

I was under the impression that we wanted to keep Location support, and replace Local with a ChainTZ parameter; but it seems that we removed Location and ChainTZ is a fixed variable, not a paramter; can you elaborate if possible?

My current thinking about what we want, and sorry again for the slow turnaround:

- Location support, but removing the native functions and loading from system tzdata (too reliant on host system, error-prone)
	- So removing LoadLocation, but keeping LoadLocationFromTZData (allows to have user-created packages with location information)
- `ChainTZ()` as a function which returns the chain `*Location`, uses a native function which returns the TZData of the chain, but right now only do a mock implementation which returns `""` and as such ChainTZ returns `UTC`.

The monotonic changes look good.

Thanks!

2025-04-01 19:13 UTC, MikaelVallenet commented on gnovm/stdlibs/time/time.gno
> +	nsec int32
No worries,
I might have misinterpreted the intent — I thought we wanted to remove the concept of "location" from the time object. But you're right, keeping location support could be useful for certain use cases, so I'll update it ASAP.

Regarding the parameters, I got feedback from Manfred suggesting that it's better to make it a constant parameter or define it at genesis, or even just have it as a simple constant inside the init function.
https://github.com/gnolang/gno/pull/3193#issuecomment-2528758311

However, I'm not entirely sure what he means by "dynamic constant."

2025-04-02 12:20 UTC, thehowl commented on gnovm/stdlibs/time/time.gno
> +	nsec int32
I think we should have it as loaded from a parameter during init(); but expose it as a normal variable, ie. not make it `ChainTZ()` but `var ChainTZ = NewLocationFromTZData("Chain", chainTZParamData())`

2025-04-08 16:08 UTC, MikaelVallenet commented on gnovm/stdlibs/time/format.gno
> +		buf = append(buf, "time.ChainTZ"...)
not sure we want this, it was time.Local... before

2025-04-08 22:13 UTC, thehowl approved these changes

2025-04-08 22:13 UTC, thehowl commented on gnovm/stdlibs/time/timezoneinfo.go
> +}
```suggestion
func X_chainTZParamData() []byte {
	return nil
}
```

2025-04-08 22:13 UTC, thehowl commented on gnovm/stdlibs/time/format.gno
> +		buf = append(buf, "time.ChainTZ"...)
It's OK

2025-04-08 22:16 UTC, thehowl commented on gnovm/stdlibs/time/timezoneinfo.go
> +}
@moul Ideally we'd have this load from the params keeper, but it seems tricky to do this and probably not ideal (because the `*SDKParams` which is passed down to the VM only has setters).

Do you think it's OK to only have the stub, and assume different chains would have a different implementation here?

2025-04-08 22:37 UTC, leohhhn commented
Hey guys, is there anything we should update in the docs in relation to stdlibs or time.time?

2025-05-15 07:44 UTC, thehowl commented
@MikaelVallenet can you update with master?

I'll hassle manfred to review this afterwards ;)

2025-05-16 12:40 UTC, MikaelVallenet commented
> @MikaelVallenet can you update with master?
> 
> I'll hassle manfred to review this afterwards ;)

no worries, done

2025-05-17 12:33 UTC, moul commented on gnovm/stdlibs/time/format.gno
> +		buf = append(buf, "time.ChainTZ"...)
I think we should just keep Local. Is there any problem justifying that we want to create a discrepancy with go?

2025-05-17 12:40 UTC, moul commented on gnovm/stdlibs/time/timezoneinfo.gno
> -	// "syscall" XXX
We want to keep these, to indicate what changed with upstream go.

2025-05-19 08:37 UTC, MikaelVallenet commented on gnovm/stdlibs/time/format.gno
> +		buf = append(buf, "time.ChainTZ"...)
IMO, Is it about that local was based on the user local system implying it could be error-prone or unstable.
Now we inject the timezone data.

So do you consider keeping the naming ``Local`` but just modify how it's fetch or you consider the PR should just not modify anything related to the timezone ?

2025-05-19 08:40 UTC, MikaelVallenet commented on gnovm/stdlibs/time/timezoneinfo.gno
> -	// "syscall" XXX
[2f26e54](https://github.com/gnolang/gno/pull/3193/commits/2f26e5418f7c7da6701ec2b787523b3140055f2f)

2025-05-26 15:54 UTC, moul commented
No, sorry, I probably forgot to send my feedback. I do have some, so let me mark this PR as blocked until I write it all down.

2025-05-26 15:55 UTC, moul requested changes
wait my feedback please

2025-05-26 15:57 UTC, moul commented on gnovm/stdlibs/time/timezoneinfo.gno
> +var ChainTZ *Location = &chainLoc
What about simply naming it `Local`? The `time.Local` function was removed, which will cause issues. If we want to establish a notion of "local for the user," we need to approach it from the gnoweb (and other clients) perspective. This will ensure the expected timeshift occurs automatically between chain.local and computer.local.

2025-05-26 16:02 UTC, moul commented on gnovm/stdlibs/time/timezoneinfo.gno
> -func LoadLocation(name string) (*Location, error) {
Why remove it?  
This isn't simplification; it's the removal of a feature we expect to function in a well-known standard library package.  
Simplification should focus on making it easier to use or  something you shouldn't have to worry about.

2025-05-27 08:45 UTC, MikaelVallenet commented on gnovm/stdlibs/time/timezoneinfo.gno
> -func LoadLocation(name string) (*Location, error) {
Read more about this here
https://github.com/gnolang/gno/pull/3193#discussion_r2023454656

2025-05-27 12:26 UTC, MikaelVallenet commented on gnovm/stdlibs/time/timezoneinfo.gno
> +var ChainTZ *Location = &chainLoc
Agree & fix: [6aab885](https://github.com/gnolang/gno/pull/3193/commits/6aab8851d32c9d90d60fbc76c8e5e1f6debb6fe2)

2025-05-28 13:30 UTC, moul commented on gnovm/stdlibs/time/timezoneinfo.gno
> +}
Related -> https://github.com/gnolang/gno/pull/4291

2025-05-28 13:36 UTC, moul commented
Continues https://github.com/gnolang/gno/pull/3193#discussion_r2111944020

As a rule of thumb, this PR affects a standard library package. The standard library is where we aim to establish the most common behavior in Go, particularly by ensuring a compatible API.

Each time we diverge, it should be for a clear reason. Most of the content in this PR appears to be opinionated UX changes that are being enforced. We should just focus on fixing what doesn't make sense. For example, Local should represent the chain metadata, not the system host, which should be consistent across all validators.

The changes should be minimal and documented with comments to facilitate easy porting to a more recent version.

2025-05-28 13:37 UTC, moul commented on gnovm/stdlibs/time/timezoneinfo.gno
> +// Local represents the chain's local time zone.
Help Git by adding the line back at the same location as before. It should be a no-diff instead of a dual diff.

2025-06-02 14:39 UTC, mvallenet commented
I revert to keep only the removal of monotonic clock related code.
I'd like to have more hints / informations on what is expected and how i should integrate it
IMO, we want a timezone `(defined at genesis?)` shared by all the nodes that does not rely on host system
If i'm on the right track my question is what is the way do to this ? 
cc @moul cc @thehowl cc @jaekwon

2025-07-07 02:04 UTC, jaekwon commented
> /summon @jaekwon

always late, but looking at it now

2025-09-03 09:09 UTC, thehowl commented
<img width="1023" height="1273" alt="image" src="https://github.com/user-attachments/assets/7362b9e9-67f1-4f77-9ff1-52cb378d0656" />

@MikaelVallenet we're good to fix it up :)

2025-09-03 10:47 UTC, thehowl commented
finally, let's merge this!

2025-09-03 10:47 UTC, merged

2025-09-03 10:52 UTC, MikaelVallenet commented
> finally, let's merge this!

:tada: :tada: