Add gno implementation of crypto/bech32
gnolang/gno pull request #3375
Opened 2024-12-19 15:11 UTC by Villaquiranm

Related to #1475

2025-01-06 16:54 UTC, n2p5 requested changes
This looks really good, I have a note on a comment you left in the code, but it otherwise seems like a pragmatic and straightforward PR. 

Open question here: For libraries that we port from go -> gno. Do we have an established pattern where I can use some reference data, expected inputs and outputs, and run both the go and gno implementations to show that I get the exact same outputs between both systems? It seems like this would be a really nice way to prove feature parity.

2025-01-06 16:54 UTC, n2p5 commented on examples/gno.land/r/demo/keystore/keystore_test.gno
> +	var (
This comment either needs context that you changed const -> var, or the comment should be removed and become its issue tracked on why this behavior does not work. This way, the coding implementation stays clean. 

From an implementation standpoint, I don't see a problem with this being `var` since it is scoped to the test itself and, therefore, doesn't need a note. It is an interesting question to explore on its own merit though.

2025-01-07 21:39 UTC, Villaquiranm commented on examples/gno.land/r/demo/keystore/keystore_test.gno
> +	var (
Hello, thanks a lot for the review :)
yeah I add that in order to give some context on my change

I prefered to leave a comment instead of just changing const -> var without an explanation 
I think there is an issue to be created, but the issue make sense only if the code is merged. 

I agree with you and I'll remove this comment as soon as the Issue is created but I don't really know like do I create the issue right away ? or we wait for the PR to be close to be merged ?

2025-01-08 08:10 UTC, jefft0 commented
Removed the `review/triage-pending` label because this PR was reviewed by core dev n2p5.

2025-01-08 15:32 UTC, n2p5 commented on examples/gno.land/r/demo/keystore/keystore_test.gno
> +	var (
Right, but if we are to leave the comment, the comment needs to mention that you've changed this from const to var in the comment. if you look at only the lines added and not the lines removed, it doesn't let the reader know that you've replaced const with var. So, if you leave the comment, consider elaborating on the context.

The reason I think removing the comment is that const doesn't provide any additional safety here. This lives inside of a testing file and we don't have to worry about mutation here.

2025-01-08 21:50 UTC, Villaquiranm commented on examples/gno.land/r/demo/keystore/keystore_test.gno
> +	var (
Sorry you're right, I thought I specified that change...
Improved the (temporary comment, I hope) on bf2167bce82c1f742f9342584d825e82080704aa

2025-01-08 22:09 UTC, n2p5 approved these changes
LGTM

2025-01-13 12:31 UTC, merged