feat: add JJOptimist's Homepage realm to examples
gnolang/gno pull request #3405
Opened 2024-12-25 12:05 UTC by JJOptimist

This pull request adds a new realm example to the Gno examples repository—JJOptimist's Homepage.

The realm includes:
- Personal introduction and contact information
- Configuration management system
- Owner controls 
- Tests for ownership and rendering

2024-12-25 12:06 UTC, Gno2D2 commented
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)
- [ ] The pull request description provides enough details


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: JJOptimist/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

<details><summary>The pull request description provides enough details</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 Not (🔴 Pull request author is a member of the team: core-contributors)

```
### Can be checked by
 - team core-contributors

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

2024-12-27 04:38 UTC, leohhhn requested changes
Please check comments 🙏 

Apart from that, if you want to merge something into the `examples/` folder, it should provide some educational value about Gno to newcomers. Please, explore a bit more and see what interesting realms or packages you can use to make your home realm more unique, so that it can be merged into the monorepo. 

If you do not want to do this, you can simply deploy persmissionlessly.

2024-12-27 04:38 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/config.gno
> +
Unnecessary newline

2024-12-27 04:38 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/config.gno
> +    owner = OWNER_ADDR
If you're defining this at top-level, you can simply initiate it where you declared it. 

This is a bit of a blurry line in Gno, so bear with me- following Go standards, if you can declare+initialize something immediately, do so at top level; `init` should be reserved for "doing" things you cannot do at declaration+initialization.

2024-12-27 04:38 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/config.gno
> +    owner std.Address
Why not use `p/demo/ownable`?

2024-12-27 04:38 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/config.gno
> +} {
Nit: I think there is no need to fold this line

2024-12-27 04:38 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home_test.gno
> +
Random newline

2025-01-09 20:45 UTC, leohhhn commented
Hey @JJOptimist, what's the status of this PR?

2025-01-09 23:50 UTC, JJOptimist commented
> Hey @JJOptimist, what's the status of this PR?
> 
I fixed the things you pointed out and took your suggestion to use ownable. Ive been experimenting to make something creative/ worth the HoF, so i will push it all together soon

2025-01-10 15:31 UTC, JJOptimist commented
I've updated the realm

- Integrated `p/demo/ownable` for proper ownership management and access control
- Added dynamic ASCII art gnome that changes based on block height
- Moved files to `home/` directory structure
- Added proper tests for both ownership and configuration

The gnome's expression changes based on block height divisibility (by 2, 3, 5, or 7)

2025-01-10 15:33 UTC, jefft0 commented on mykey_backup.armor
Should this file be removed?

2025-01-10 15:33 UTC, leohhhn commented on mykey_backup.armor
Leftover file?

2025-01-10 15:37 UTC, leohhhn commented
@JJOptimist 

Generally, please take a look at comments and reply to them, even if they're outdated because you've changed the code completely.

2025-01-13 11:03 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/config.gno
> +    owner std.Address
Great suggestion, I've integrated `p/demo/ownable` for better ownership management in my latest changes.

2025-01-13 11:11 UTC, JJOptimist commented
Thanks for your patience. Let me explain the code evolution:

Initially, I tried to create an animated realm with CSS animations. However, I discovered that complex CSS animations weren't the best approach for a Gno realm, as:
   - CSS animations added unnecessary complexity
   - The focus should be on demonstrating Gno-specific features
   - Markdown rendering is more reliable for realm display

2025-01-14 21:21 UTC, leohhhn requested changes
Good start; please fix the things I mentioned in the comments below :)

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home_test.gno
> +}
You generally don't need to test functionality of another imported package; what you should do, ideally, is check the package code, and verify its tests. If they're satisfactory, you opt into using the package. 

By doing what you did in the code, you're creating boilerplate and taking up unnecessary space on the chain :)

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home.gno
> + -"-`
These can be `consts`, no?

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/gno.mod
> +)
The `require` keyword was removed a month or so ago. This will make tests & the CI fail

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +    }
You can use `o.AssertCallerisOwner`

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +    "gno.land/p/demo/ownable"
Nitpick-` stdlibs`,`p/` & `r/` should be spaced out:

```suggestion
    "std"
    
    "gno.land/p/demo/ownable"
```

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +}
Redundant if you export `Ownable`

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +var o = ownable.NewWithAddress(std.Address("g16vfw3r7zuz43fhky3xfsuc2hdv9tnhvlkyn0nj"))
```suggestion
var Ownable = ownable.NewWithAddress(std.Address("g16vfw3r7zuz43fhky3xfsuc2hdv9tnhvlkyn0nj"))
```

`Ownable` should be exported. By exporting a struct such as `ownable`, you also export all of it's methods, which are required to do anything with the owner, such as transfer ownership or drop it. With your implementation it's impossible to update the owner :)

Look into "safe objects" (search the examples folder for this), and read into MsgCall and MsgRun

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home.gno
> +    return "```\n" + art + "\n```\n"
Nit: check how this would look with a switch

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +}
This is just ugly; define this `config` struct properly.

2025-01-14 21:21 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home.gno
> +    cfg := GetConfig()
Since this is the same package, just reference the existing `config` object.

2025-01-14 21:57 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home.gno
> +}
Also register to the hall of fame :)

2025-01-19 15:51 UTC, JJOptimist commented
I've updated the home realm:

- Changed gnome art variables to constants for better code organization
- Replaced if-else chain with switch statement for cleaner gnome art selection
- Properly defined Config struct with exported fields for better type safety
- Exported Ownable and implemented AssertCallerIsOwner for proper access control
- Removed redundant GetOwner() function since Ownable is now exported
- Changed `require` to `dependencies` in gno.mod following new standards
- Properly spaced out imports for better readability
- Registered realm in Hall of Fame for community visibility
- Removed ownership tests to avoid testing imported package functionality
- Using direct config access in same package for better efficiency

2025-01-20 18:51 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/home.gno
> + -"-`
Yes, first idea was for them to have animations but now that they are static it makes more sense to be `consts`.

2025-01-20 18:51 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/home_test.gno
> +}
I removed unnecessary tests for imported packages.

2025-01-20 18:51 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/config.gno
> +    "gno.land/p/demo/ownable"
Noted, i will be separating them from now on.

2025-01-20 19:06 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/config.gno
> +var o = ownable.NewWithAddress(std.Address("g16vfw3r7zuz43fhky3xfsuc2hdv9tnhvlkyn0nj"))
Thanks for explaining this! I've exported `Ownable` as suggested. I've checked MsgRun and how cross-realm method calling works

2025-01-20 19:08 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/home.gno
> +}
Registered ✔

2025-01-20 19:10 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/gno.mod
> +)
I removed it. At first, i didn't check all the tests I wrote for my realm and thought that was the thing making it fail but in the end, it was `require`.

2025-01-20 19:11 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/home.gno
> +    return "```\n" + art + "\n```\n"
Changed to switch and looks cleaner now

2025-01-20 19:14 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/config.gno
> +}
I've removed the redundant `GetOwner()` function since I am now exporting `Ownable`. Users can directly call `Ownable.Owner()` to get the owner's address, making the wrapper function unnecessary.

2025-01-20 19:16 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/home.gno
> +    cfg := GetConfig()
Updated, I'm using `config` directly now

2025-01-20 19:20 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/config.gno
> +    }
I've updated the code to use `Ownable.AssertCallerIsOwner()` instead of the manual check. It uses the built-in assertion, thanks for the suggestion

2025-01-20 19:21 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/config.gno
> +}
Updated , much cleaner now

2025-01-21 10:08 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +
```suggestion

```

2025-01-21 10:09 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home.gno
> +)
```suggestion
var creation time.Time
```

2025-01-21 10:12 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home.gno
> +}
Move this to the bottom or somewhere else, since this is a helper function

2025-01-28 22:07 UTC, leohhhn approved these changes
Just check the leftover comments, and run `make fmt` in examples :)

2025-01-28 22:07 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +var Ownable = ownable.NewWithAddress(std.Address("g16vfw3r7zuz43fhky3xfsuc2hdv9tnhvlkyn0nj"))
```suggestion
var (
	config = Config {
	    Title:       "JJOptimist's Home Realm 🏠",
	    Description: "Exploring Gno and building on-chain",
	    Github:      "jjoptimist",
	}
	Ownable = ownable.NewWithAddress(std.Address("g16vfw3r7zuz43fhky3xfsuc2hdv9tnhvlkyn0nj"))
)
```

2025-01-28 22:07 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/home.gno
> +    "gno.land/p/demo/ownable"
This is unused

2025-01-28 23:27 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/home.gno
> +}
Done in [this commit](https://github.com/user/repo/commit/b2e6f03) again after revert.

2025-01-28 23:31 UTC, JJOptimist commented on examples/gno.land/r/jjoptimist/home/home.gno
> +    "gno.land/p/demo/ownable"
Removed the one causing test to fail in [commit](https://github.com/gnolang/gno/pull/3405/commits/d674a91057228cf738f635f0f7c8c012fe10e501)

2025-02-04 12:27 UTC, leohhhn commented
Hey it seems you have a bit of an issue with the diff. Can you just have the files you're trying to add?

2025-02-04 13:23 UTC, JJOptimist commented
> Hey it seems you have a bit of an issue with the diff. Can you just have the files you're trying to add? After that we can merge.

Removed from cache👍

2025-02-05 11:20 UTC, leohhhn commented on examples/gno.land/r/jjoptimist/home/config.gno
> +
```suggestion
}

var Ownable = ownable.NewWithAddress(std.Address("g16vfw3r7zuz43fhky3xfsuc2hdv9tnhvlkyn0nj"))

```

2025-02-05 11:21 UTC, leohhhn approved these changes

2025-02-05 11:32 UTC, merged