dev/moul/pageable
gnolang/gno pull request #3414
Opened 2024-12-27 22:01 UTC by moul

- **feat(examples): add moul/ulist**
- **chore: fixup**
- **chore: fixup**
- **chore: fixup**
- **chore: fixup**
- **chore: fixup**
- **chore: fixup**
- **chore: fixup**
- **feat(examples): add moul/pageable**
- **chore: fixup**

2024-12-27 22:02 UTC, Gno2D2 commented
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: moul/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

2025-01-23 18:18 UTC, n2p5 requested changes
I know this is still in draft, but I took a look over the code and it is looking really nice. I put in a couple of notes and pointed out one place that you could avoid type conversions with a fun math trick. Let me know when its out of draft. I like this structure a lot.

2025-01-23 18:18 UTC, n2p5 commented on examples/gno.land/p/moul/pageable/pageable.gno
> +		totalPages = int(math.Ceil(float64(totalItems) / float64(pageSize)))
This can be more simply implemented as

```go
totalPages = (totalItems + pageSize - 1) / pageSize
```

This avoids the need for type conversions.

2025-02-24 20:06 UTC, moul commented
Related with https://github.com/gnolang/gno/pull/3806
TODO: link to @jeronimoalbi's alternative

2025-09-29 09:24 UTC, jeronimoalbi commented on examples/gno.land/p/moul/pageable/pageable.gno
> +//   - gno.land/p/demo/avl/pager: implementation for AVL trees.
```suggestion
//   - gno.land/p/nt/avl/pager: implementation for AVL trees.
```

2025-09-29 09:33 UTC, jeronimoalbi commented on examples/gno.land/p/moul/pageable/pageable.gno
> +		totalPages = int(math.Ceil(float64(totalItems) / float64(pageSize)))
Nice one 👍

2025-09-29 09:38 UTC, jeronimoalbi commented on examples/gno.land/p/moul/ulist/pager/gnomod.toml
> +)
```suggestion
```

2025-09-29 09:50 UTC, jeronimoalbi commented on examples/gno.land/p/moul/pageable/pageable.gno
> +	// - In reverse mode: offset 0, count 5 would return items [4,3,2,1,0]
Wouldn't this actually be the following?
```suggestion
	// - In reverse mode: offset 0, count -5 would return items [4,3,2,1,0]
```

2025-09-29 10:05 UTC, jeronimoalbi commented
PR looks good already 👍

2026-06-24 16:23 UTC, thehowl commented
Closing as 1.5yr stale

2026-06-24 16:23 UTC, closed without merging