feat(cmd/gno): pkgaddr subcommand
gnolang/gno pull request #3416
Opened 2024-12-28 13:51 UTC by n0izn0iz

Adds a `gno` sub-command called `pkgaddr` that takes a pkgpath as argument and outputs the corresponding pkgaddr using `gnolang.DerivePkgAddr'

Example usage:
```
> gno pkgaddr gno.land/r/demo/users
g17m4ga9t9dxn8uf06p3cahdavzfexe33ecg8v2s
```

2024-12-28 13:52 UTC, Gno2D2 commented
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: n0izn0iz/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

2024-12-29 07:51 UTC, moul commented
We should find a better way to manage the "not go related subcommands." This could involve creating a dedicated subcommand category for these helpers, using a prefix, or simply placing everything in contribs/.

I suggest starting with contribs/. It could be in gnodev if we believe there's a daily need for it (I don't think there is, cc @gfanton), or we could create a new tool. A contribs/gnoconv generic binary for such operations might make sense and could pave the way for other similar helpers until we find a way to integrate these usages more effectively (or not).

2024-12-29 07:51 UTC, moul requested changes
We should find a better way to manage the "not go related subcommands." This could involve creating a dedicated subcommand category for these helpers, using a prefix, or simply placing everything in contribs/.

I suggest starting with contribs/. It could be in gnodev if we believe there's a daily need for it (I don't think there is, cc @gfanton), or we could create a new tool. A contribs/gnoconv generic binary for such operations might make sense and could pave the way for other similar helpers until we find a way to integrate these usages more effectively (or not).

2025-03-11 18:26 UTC, thehowl commented
Closing as not planned

2025-03-11 18:26 UTC, closed without merging

2025-03-12 03:24 UTC, n0izn0iz commented
I use the repl for that now :)