feat(test): handle empty args by assuming current directory for gno test
gnolang/gno pull request #3429
Opened 2024-12-30 17:19 UTC by Nemanya8

This PR addresses Issue #3420 by improving the gno test command. It now assumes the current directory (.) as the default path when no directory is specified, similar to go test.

2024-12-30 17:20 UTC, Gno2D2 commented
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)
- [ ] The pull request description provides enough details


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 The pull request was created from a fork (head branch repo: Nemanya8/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

<details><summary>The pull request description provides enough details</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 Not (🔴 Pull request author is a member of the team: core-contributors)

```
### Can be checked by
 - team core-contributors

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>

2024-12-30 18:40 UTC, Nemanya8 commented
The test case for no arguments currently fails, which is expected due to the changes. However, if we are moving forward with this merge, the test case should be updated accordingly. Please let me know if you'd like me to handle the update.

2024-12-31 10:01 UTC, notJoon commented
> the test case should be updated accordingly. Please let me know if you'd like me to handle the update.

I confirmed that it runs well when executed locally. It seems we need to make the CI pass, so could you modify the tests if possible?

2024-12-31 14:55 UTC, Nemanya8 commented
> so could you modify the tests if possible?

Could you guide me on modifying the tests? Should I only adjust the test with no arguments, or should I add a variation without path arguments for each test? The latter approach is more thorough, but it would basically double the testing time.

2024-12-31 17:45 UTC, moul requested changes
need some unit or integration tests.

2025-01-05 16:09 UTC, closed without merging