Update testutils.go atom -> ugnot
gnolang/gno pull request #366
Opened 2022-10-21 09:35 UTC by piux2

2022-10-23 19:11 UTC, moul commented
Can you fix failing tests?

2022-10-27 11:11 UTC, moul commented on pkgs/sdk/testutils/testutils.go
> +
```suggestion	
```

Can you try to configure your IDE to run linting tools like gofumpt automatically?

2022-10-27 11:12 UTC, moul requested changes
Can you fix the tests please?

2023-01-21 04:02 UTC, piux2 commented
No need to change it.  close.

2023-01-21 04:02 UTC, closed without merging