Fix: file tests should have failed in Github CI. Added sync flag to sync the wanted and actual results for local testing
gnolang/gno pull request #449
Opened 2023-01-05 23:53 UTC by piux2

# Description

#440 3 of 3

This commit is the last step to fixing the false testing result during Github CI
We keep the feature to sync the actual output to test comments in files. It allowed us to see wanted outcomes overwritten by actual results during local testing. "Git status" shows modified testing files.

1) Added a syncWanted parameter to the RunFileTest() in tests/file.go and runFileTest() in tests/file_test.go. It makes the function contract clear without relying upon the side effect of the syncWanted variable while we still maintain the custom testing flag available in file_test.go for the Makefile to execute in CI. 

2) Set package variable syncWanted as a golang custom testing flag --sync in tests/file_test.go. The default value is false. It allows the CI  to stop at failure cases when executing file tests in the tests/files and tests/files2  folder 

3) Added --sync flog in cmd/gnodev/test.go. The default value is false. It allows CI to stop at failure cases when executing file tests in ./examples

4) Added three entries in the Makefile. It allows us to turn on the sync flag during the local testing
  test.files1.sync
  test.files2.syn
  test.examples.sync

5) To run tests/files and tests/files2 file test with sync on

	   go test ./tests -v --sync

6) To run file test in ./examples with sync on 

	   ./build/gnodev test ./examples --sync

# How has this been tested?

1) Modify the realm hash in 

    tests/files/zrealm_example.gno
    tests/files2/zrealm_example.gno

    make test.files1 - failed
    make test.files2 - failed

    make test.files1.sync - passed
    make test.files2.sync - passed
 
    The correct hash value was written back to the file test comments. 

2) Replaced print with println in examples/gno.land/r/demo/releases-example/release0_filetest.gno

    make test.examples - failed

    make test.examples.sync - failed

    The correct rendering output was written back to the file test comments.

2023-01-16 15:09 UTC, zivkovicmilos approved these changes
Looks great 💯 

Thank you for the contribution as always 🙏

2023-01-19 18:18 UTC, moul commented on Makefile
> +	go test tests/*.go -v -test.short -run "TestFiles1/" --timeout 30m	--sync
```suggestion
	go test tests/*.go -v -test.short -run "TestFiles1/" --timeout 30m --sync
```

2023-01-19 18:20 UTC, moul approved these changes

2023-01-19 18:22 UTC, moul requested changes
thank you very much for this contrib. However, I think `sync` is too ambiguous and risks conflicting with a potential upcoming feature.

what do you think about renaming `--sync` to `--update-golden-tests`?

2023-01-20 19:32 UTC, piux2 commented
> thank you very much for this contrib. However, I think `sync` is too ambiguous and risks conflicting with a potential upcoming feature.
> 
> what do you think about renaming `--sync` to `--update-golden-tests`?

Sure, that makes sense. I will update it.

2023-02-18 04:40 UTC, piux2 commented
> thank you very much for this contrib. However, I think `sync` is too ambiguous and risks conflicting with a potential upcoming feature.
> 
> what do you think about renaming `--sync` to `--update-golden-tests`?

@moul can you approve this?

2023-02-18 21:04 UTC, moul approved these changes

2023-02-18 23:38 UTC, merged