perf: use swiss map for the object cache
gnolang/gno pull request #677
Opened 2023-03-30 13:14 UTC by peter7891

This PR uses `swiss` map for the object cache.
Detailed benchmarks in this blog https://www.dolthub.com/blog/2023-03-28-swiss-map/

I've verified these are correct.
We should consider using this map in other places as well.
For example, in the implementation of the builtin map in Gno.

2023-03-30 14:07 UTC, peter7891 commented
Detailed benchmarks in this blog https://www.dolthub.com/blog/2023-03-28-swiss-map/

I've verified these are correct.

2023-04-01 17:44 UTC, moul commented
Hey @peter7891, could you provide more detailed benchmarks for our code, including measuring the execution time of a Gno contract? Also, do you have any suggestions for a benchmarking framework that we can use to centralize our performance history and optimization documentation?

2023-04-03 07:08 UTC, moul requested changes
Depends on #689

2023-04-06 11:38 UTC, peter7891 commented
Let's wait until we have the tool, to merge this.
In the mean time, on a heap with a thousand objects.

`Fetching objects on master`
```
BenchmarkWriteReadLargeHeap-8                 70          17094023 ns/op
```
`Fetching objects on this branch`
```
BenchmarkWriteReadLargeHeap-8                 62          14150240 ns/op
```

This is a large improvement and it gets better tha larger the heap is.

2023-05-06 16:54 UTC, moul commented
Following a recent discussion, we have reconsidered our position, let's merge PRs freely for now, but keep the perf dashboard (#689) as a future goal.

Please provide benchmarks with larger heap size to help achieve this. Thanks.

2023-05-08 11:28 UTC, peter7891 commented
> Following a recent discussion, we have reconsidered our position, let's merge PRs freely for now, but keep the perf dashboard (#689) as a future goal.
> 
> Please provide benchmarks with larger heap size to help achieve this. Thanks.

I added benchmarks for the maps themselves.

```
BenchmarkSwissMap
BenchmarkSwissMap-10    	15304465	        76.86 ns/op
BenchmarkMap
BenchmarkMap-10    	13462977	        90.45 ns/op
```

In the larger context of the heap, it makes less of a different because the other operations around it add a lot more runtime costs. So i am not sure if making this change is worth making now.
Further changes will be made when the GC/runtime PR gets merged.
I think, it might be better to wait until then and see if this is even necessary.

2025-08-13 08:21 UTC, thehowl commented
Closing as stale.

2025-08-13 08:21 UTC, closed without merging