feat(cli): add listen flag
gnolang/gno pull request #729
Opened 2023-04-11 17:06 UTC by albttx

# Description

This PR add a `-listen` flag to be able to listen on `0.0.0.0` inside a docker container

2023-04-11 21:51 UTC, moul commented on gno.land/cmd/gnoland/main.go
> +		"tcp://127.0.0.1:26657",
This string is used 3 times in this file, and should be a constant. This constant should probably be located in a pkg, and not in the main.

2023-04-11 21:52 UTC, moul commented on gno.land/cmd/gnoland/main.go
> +	}
This is not the way to manage this. Instead, you should parse flags directly against the unmarshalled config file.

2023-04-11 21:55 UTC, moul requested changes
I'm not in favor of this shortcut because it creates an inconsistent exception, doesn't reuse the existing constants, and isn't linked with the existing configuration structure.

Please, check #731.

2023-06-16 19:20 UTC, thehowl commented
Shall we close this?

2023-06-17 06:58 UTC, closed without merging