feat: native bigint using math/big.Int
gnolang/gno pull request #764
Opened 2023-04-20 05:53 UTC by r3v4s

# Description

This is separated PR which includes only `bigint` from #676

## Types that can be converted to bigint
- int
- int32
- int64
- uint
- uint32
- uint64 

# How has this been tested?

`bigint_test.gno`

# Benchmark & Performance 
```
goos: darwin
goarch: arm64
Benchmark_Int64Add-10     	1000000000	         0.0004173 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Add-10     	1000000000	         0.0003738 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Add-10     	1000000000	         0.0003746 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Add-10    	1000000000	         0.0003738 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Add-10    	1000000000	         0.0003744 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Add-10    	1000000000	         0.0003477 ns/op	       0 B/op	       0 allocs/op
Benchmark_BigintAdd-10    	1000000000	         0.007314 ns/op	       	       0 B/op	       0 allocs/op
Benchmark_BigintAdd-10    	1000000000	         0.007358 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintAdd-10    	1000000000	         0.007335 ns/op	               0 B/op	       0 allocs/op
Benchmark_Int64Sub-10     	1000000000	         0.0003242 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Sub-10     	1000000000	         0.0003167 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Sub-10     	1000000000	         0.0003189 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Sub-10    	1000000000	         0.0003235 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Sub-10    	1000000000	         0.0003245 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Sub-10    	1000000000	         0.0003221 ns/op	       0 B/op	       0 allocs/op
Benchmark_BigintSub-10    	1000000000	         0.008838 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintSub-10    	1000000000	         0.008850 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintSub-10    	1000000000	         0.008864 ns/op	               0 B/op	       0 allocs/op
Benchmark_Int64Mul-10     	1000000000	         0.0003225 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Mul-10     	1000000000	         0.0003163 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Mul-10     	1000000000	         0.0003220 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Mul-10    	1000000000	         0.0003220 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Mul-10    	1000000000	         0.0003221 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Mul-10    	1000000000	         0.0003216 ns/op	       0 B/op	       0 allocs/op
Benchmark_BigintMul-10    	1000000000	         0.008035 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintMul-10    	1000000000	         0.008328 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintMul-10    	1000000000	         0.008106 ns/op	               0 B/op	       0 allocs/op
Benchmark_Int64Div-10     	1000000000	         0.0006240 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Div-10     	1000000000	         0.0006945 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Div-10     	1000000000	         0.0006245 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Div-10    	1000000000	         0.0006283 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Div-10    	1000000000	         0.0006655 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Div-10    	1000000000	         0.0006413 ns/op	       0 B/op	       0 allocs/op
Benchmark_BigintDiv-10    	1000000000	         0.01054 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintDiv-10    	1000000000	         0.01056 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintDiv-10    	1000000000	         0.01055 ns/op	               0 B/op	       0 allocs/op
Benchmark_Int64Mod-10     	1000000000	         0.0006245 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Mod-10     	1000000000	         0.0006695 ns/op	       0 B/op	       0 allocs/op
Benchmark_Int64Mod-10     	1000000000	         0.0006420 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Mod-10    	1000000000	         0.0006414 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Mod-10    	1000000000	         0.0006415 ns/op	       0 B/op	       0 allocs/op
Benchmark_Uint64Mod-10    	1000000000	         0.0006413 ns/op	       0 B/op	       0 allocs/op
Benchmark_BigintMod-10    	1000000000	         0.009151 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintMod-10    	1000000000	         0.009131 ns/op	               0 B/op	       0 allocs/op
Benchmark_BigintMod-10    	1000000000	         0.009112 ns/op	               0 B/op	       0 allocs/op
PASS
```

# Additional
there is #761 issue about memory allocations

2023-04-28 09:53 UTC, dongwon8247 commented
@jaekwon @moul @thehowl Would love to have your feedback on this PR :)

2023-04-28 12:54 UTC, moul requested changes
Implementation looks good (need advanced review), but let's discuss #676 before adding a new keyword.

Edit: #676 was a closed PR. Since it has the most history, we can continue on that or open a new issue. It's up to you.

2023-05-02 09:58 UTC, ajnavarro commented
Sorry for my ignorance, but why don't just stick with the standard way to handle bigints in Go, using "math/big"?

2023-05-03 17:07 UTC, moul commented
> Sorry for my ignorance, but why don't just stick with the standard way to handle bigints in Go, using "math/big"?

Thanks for your question.

The only required component is the implementation and availability of `math/big`.

The proposed extension with `bigint` keyword aims to better support big integer usage in DeFi contracts, potentially simplifying code and ensuring compatibility with existing Go code via `gno precompile`.
Although optional, the feature is straightforward and beneficial enough to justify a consideration of its advantages and drawbacks.

2023-05-12 08:19 UTC, thehowl commented
@r3v4s Could you share how you're doing benchmarks? Unless you have a supercomputer, `0.009112 ns/op` is veeeery unlikely (are you just calling the function in the benchmark or are you iterating with `for i := 0; i < b.N; i++`?)

I still think that the best course of action for Gno would be to have uint256/128 instead of bigint, at least initially, as I think they have fewer memory usage implications than bigint.

Do you have examples of applications where you think bigints make sense as compared to a uint256?

2023-12-07 04:52 UTC, r3v4s commented
@moul synced pr branch with latest master, there will be no more conflicts for now. However CI is failing because it precompiles `.gno` to `gen.go` and unfortunately go doesn't support `bigint` keyword.

OTH, about using `math/big` as a temporary solution it might be possible when gno has full(or at least partial) compatibility about `math/big` with go
https://github.com/gnolang/gno/blob/a4c7b860cdff285106873b91452c11987cd385c9/docs/reference/go-gno-compatibility.md?plain=1#L198

2023-12-07 06:48 UTC, moul commented
`math/big` might pose a problem with `gnokey maketx call`, as it may not recognize this new type.

Your best alternative could be to use a smaller type, like `uint64`.

Although I'm keen on offering native support for larger integers, we could consider launching without this feature. Could you assess the implications of limiting to 64 bits?

Meanwhile, we'll explore how feasible it is to implement this PR or a similar solution.

2023-12-07 07:52 UTC, r3v4s commented
@moul 
currently, gnoswap uses `bigint` to avoid use of `floating` type or value.
> it's similar to uniswap because floating in EVM also has a determinism problem.

Let's say gnoswap v2(or later) will support `bigint` while v1 only uses primitive type. Because of token pair's exchange ratio in certain pool can be very narrow, we have no choice but to use `uint64`, `float64` type (with all kind of math package's function such as math.Log10).

2023-12-07 10:05 UTC, moul commented
> @r3v4s: there will be no more conflicts for now. However CI is failing because it precompiles `.gno` to `gen.go` and unfortunately go doesn't support `bigint` keyword.

To achieve this, we need to modify the gno precompile to generate a distinct yet valid Go code for this scenario.

2023-12-07 10:33 UTC, moul commented
> @moul currently, gnoswap uses `bigint` to avoid use of `floating` type or value.
> 
> > it's similar to uniswap because floating in EVM also has a determinism problem.
> 
> Let's say gnoswap v2(or later) will support `bigint` while v1 only uses primitive type. Because of token pair's exchange ratio in certain pool can be very narrow, we have no choice but to use `uint64`, `float64` type (with all kind of math package's function such as math.Log10).

What if you use `uint64` for the public functions in v1 and to use `math/big` or any other library to support internal operations such as divisions and floating point calculations. 

Once native support compatible with `maketx` is available, you can transition to v2 and simplify the implementation. 

This doesn't imply that this PR is bad or anything; it's just about making this point not a launch constraint for you but a v2/milestone constraint.

2024-05-15 05:47 UTC, thehowl commented
Closing for now as we are trialling the [uint256](https://github.com/gnolang/gno/tree/master/examples/gno.land/p/demo/uint256) package instead.

2024-05-15 05:47 UTC, closed without merging