feat(gno.land/cmd): add flag `--unsafe-reset-all`
gnolang/gno pull request #770
Opened 2023-04-21 14:18 UTC by harry-hov

# Description

Manually deleting the "testDir" directory every time during development, debugging, or testing can be inconvenient.

2023-04-21 21:20 UTC, moul commented on gno.land/cmd/gnoland/main.go
> +		"unsafe-reset-all",
```suggestion
		"unsafe-reset-before-start",
```

Maybe better this way?

Not convinced if it's logical, despite my personal interest in using the flag.

2023-04-21 21:26 UTC, zivkovicmilos commented
Why do we even need this, since we already have [a Makefile directive](https://github.com/gnolang/gno/blob/096f117157f36e6406ad0221794ee62815d31bc5/gno.land/Makefile#L24-L26) for removing the working directory?

I don't like the fact that we're cluttering the binary flag space with a development flag. These QoL additions should exist outside of the user-facing code and API

2023-04-21 21:33 UTC, zivkovicmilos requested changes
I am not convinced that adding a development flag to user binaries is the way to solve minor inconveniences - we should build tools around existing (and required-only) functionality

2023-04-21 22:23 UTC, harry-hov commented
Ignite has `--reset-once`
tendermint has `unsafe-reset-all`
all the blockchain binaries build using cosmos-sdk has `unsafe-reset-all`

I see no reason to not have something similar for gno.

2023-04-21 22:29 UTC, zivkovicmilos commented
> Ignite has `--reset-once` tendermint has `unsafe-reset-all` all the blockchain binaries build using cosmos-sdk has `unsafe-reset-all`
> 
> I see no reason to not have something similar for gno.

Just because they have it implemented doesn't justify their existence. 

What benefit do we have from adding a flag like this, that is only used during development, to the main binary that's distributed out to users?

2023-04-21 22:30 UTC, closed without merging

2023-04-22 21:39 UTC, tbruyelle commented
About the comparison with `ignite`, its ability to run a chain is only for testing purpose, it shouldn't be used in production (see usage below). So I think it's fine to provide this kind of flag in this context. On the other hand, `gnoland` can be used in production, so I agree with @zivkovicmilos.

```sh
$ ignite chain serve -h
(...)

The serve command is meant to be used ONLY FOR DEVELOPMENT PURPOSES. Under the
hood, it runs "appd start", where "appd" is the name of your chain's binary. For
production, you may want to run "appd start" manually.
```

2023-04-22 23:05 UTC, harry-hov commented
I know ignite is for development purposes. `appd`(chain-binary) is used in prod. 

As I remember, all tendermint/cosmos-based chain binaries also contain this flag. 
prev `appd start --unsafe-reset-all`
now it's moved under tendermint `appd tendermint unsafe-reset-all`

For gnoland, I believe we should have this flag. Considering most of the users are probably going to be developers and they would like to test their contracts on local instance of chain before publishing directly to the mainnet. While testing their contracts they might need to reset the blockchain's state (I might be wrong). 

@zivkovicmilos that [Makefile directive](https://github.com/gnolang/gno/blob/096f117157f36e6406ad0221794ee62815d31bc5/gno.land/Makefile#L24-L26) assumes that user will not use `--root-dir` flag.